### ISSUE TITLE
Wazuh Agent package not detected in macOS

### ISSUE THREAD

**Issue by sebasfalcone** [wazuh/wazuh-agent#104]
## Description
It was discovered that the Wazuh agent is not being detected by syscollector in macOS

This was attempted to be solved here:
- https://github.com/wazuh/wazuh/issues/15798

But the solution was too complex and it didn't make sense at the moment

## DoD
- [ ] Propose a solution
- [ ] Implement the solution

**Comment by vikman90** [comment]
## Related issues

- https://github.com/wazuh/wazuh/issues/15798
  - https://github.com/wazuh/wazuh/issues/15570

That task was closed as unplanned. Therefore, let me close this issue. We will open it back when we plan to do so.

Thanks.
