### ISSUE TITLE
how can i build wazuh-agent ?

### ISSUE THREAD

**Issue by frkn4129** [wazuh/wazuh-agent#105]
I installed the Wazuh agent using the following commands, and it worked correctly:

_wget https://packages.wazuh.com/4.x/apt/pool/main/w/wazuh-agent/wazuh-agent_4.6.0-1_amd64.deb && sudo WAZUH_MANAGER='10.1.55.221' WAZUH_AGENT_GROUP='test' WAZUH_AGENT_NAME='test_user' dpkg -i ./wazuh-agent_4.6.0-1_amd64.deb
sudo systemctl daemon-reload
sudo systemctl enable wazuh-agent
sudo systemctl start wazuh-agent_

After that, I wanted to read the source code and make some custom modifications before building it myself. However, I couldn't find the source code for the .deb agent that I installed. I checked the (https://github.com/wazuh/wazuh-agent/tree/master/src/agent), specifically the src/agent directory, but I couldn't find the parameters like AGENT_NAME, WAZUH_MANAGER, etc., and I wasn't able to run it.

How can I run it with these parameters? Could you help me please

**Comment by jr0me** [comment]
The source code for both the Agent and the Manager is in https://github.com/wazuh/wazuh

I recommend you to checkout the repository from a version tag (ie: v4.8.2).

We have detailed documentation on how to build both from sources:
* https://documentation.wazuh.com/current/deployment-options/wazuh-from-sources/wazuh-server/index.html
* https://documentation.wazuh.com/current/deployment-options/wazuh-from-sources/wazuh-agent/index.html

Let us know if you have further questions.

**Comment by frkn4129** [comment]
Hello, thank you for your feedback @jr0me . I made the desired changes and completed the build, then performed the installation using ./install.sh. I don't want to repeat the same steps on another computer, so how can I package the modified build into a .deb file?

**Comment by jr0me** [comment]
Here's a guide detailing how to create your own Wazuh packages

https://documentation.wazuh.com/current/development/packaging/generate-deb-package.html

You would need to look into checking out the repository locally, creating a branch with your changes and using it in the script mentioned in the guide.

Depending on what you're trying you may also need to modify the SPEC files for the package: https://github.com/wazuh/wazuh-packages/tree/v4.8.2/debs/SPECS/wazuh-agent/debian

Hope this helps!
