### ISSUE TITLE
Issue running .exe file after build

### ISSUE THREAD

**Issue by aais1** [wazuh/wazuh-agent#107]
I can seem to run the .exe file after buidling as it is requiring some wazuh.conf file which i could not find anywhere and the default value wouldnt work as seen in the error.

```


Using default values due to error parsing wazuh.conf file: toml::parse: error opening file "wazuh.conf"
Error: connect: No connection could be made because the target machine actively refused it [system:10061 at C:\Users\Global Computers\Desktop\whts\MUSI-Agent\src\build\vcpkg_installed\x64-windows\include\boost/asio/detail/win_iocp_socket_service.hpp:629:5 in function 'class boost::system::error_code __cdecl boost::asio::detail::win_iocp_socket_service<class boost::asio::ip::tcp>::connect(struct boost::asio::detail::win_iocp_socket_service<class boost::asio::ip::tcp>::implementation_type &,const class boost::asio::ip::basic_endpoint<class boost::asio::ip::tcp> &,class boost::system::error_code &)']
Connect failed: Connect failed: Connect failed: Error: No connection could be made because the target machine actively refused itNo connection could be made because the target machine actively refused it

Internal Server Error
No connection could be made because the target machine actively refused it
Failed to authenticate with the manager
Authentication failed.
Connect failed: Connect failed: Connect failed: No connection could be made because the target machine actively refused it
No connection could be made because the target machine actively refused it
Error: connect: No connection could be made because the target machine actively refused it [system:10061 at C:\Users\Global Computers\Desktop\whts\MUSI-Agent\src\build\vcpkg_installed\x64-windows\include\boost/asio/detail/win_iocp_socket_service.hpp:629:5 in function 'class boost::system::error_code __cdecl boost::asio::detail::win_iocp_socket_service<class boost::asio::ip::tcp>::connect(struct boost::asio::detail::win_iocp_socket_service<class boost::asio::ip::tcp>::implementation_type &,const class boost::asio::ip::basic_endpoint<class boost::asio::ip::tcp> &,class boost::system::error_code &)']
No connection could be made because the target machine actively refused it
Error: Internal Server Error
Failed to authenticate with the manager
Authentication failed.
```

**Comment by aais1** [comment]
i want to be able to run my build that is of wazuh-agent , can i somehow fix this?

**Comment by jr0me** [comment]
Some clarification, the repository for the actual Wazuh Agent (the one that it is released) is on the other repository https://github.com/wazuh/wazuh/ . This repository is currently an experimental work and hasn't been released.

**Comment by jr0me** [comment]
Here you have a guide to build the agent from sources: https://documentation.wazuh.com/current/deployment-options/wazuh-from-sources/wazuh-agent/index.html

**Comment by aais1** [comment]
Thanks. i was trying to build this and almost wasted about 3 hours
It would be nice if the readme does mention that this is experimental

**Comment by jr0me** [comment]
I'm sorry to hear this, and you have a good point. We will make that change.

**Comment by aais1** [comment]
Hey there,
Sorry to comment again but i need to be able to build this experimental repo.
And am facing issue are there docs(besides the .md files in repo) to get started with setting up the app,Thanks

**Comment by jr0me** [comment]
@aais1 development for this project has started just recently and there's not much more to do besides compiling the application and running the tests. The error you see for the missing file `wazuh.conf` is not really stopping the application from running.

**Comment by aais1** [comment]
@jr0me Just to confirm is this repo of the `Wazuh agent manager` as in screenshot below
![image](https://github.com/user-attachments/assets/82f3a9a5-f0fa-471b-bd6e-a7708709f579)

**Comment by jr0me** [comment]
Yes @aais1 that is correct. The same repository https://github.com/wazuh/wazuh is used for both Agent and Manager. When you compile the project from sources you choose which one to build when running `make` and selecting the desired target (`agent`, `server` or `manager`, and `winagent`). You might have already seen this in the documentation shared before.
