### ISSUE TITLE
Develop Service for Wazuh Agent

### ISSUE THREAD

**Issue by vikman90** [wazuh/wazuh-agent#127]
**Parent Issue:**

- https://github.com/wazuh/wazuh-agent/issues/126

## Description
This issue focuses on creating a background service for the new Wazuh agent across the supported platforms: Linux, Windows, and macOS. The service must ensure that the agent starts automatically on boot, runs in the background, and provides administrators with basic control options (start, stop, restart). 

## Functional Requirements
- **Linux**: Develop a systemd service for the agent, ensuring it integrates with systemd for all supported distributions.
- **Windows**: Implement the agent as a Windows Service, ensuring it operates correctly on Windows Server 2008 R2+.
- **macOS**: Develop a launch daemon for macOS 14+ to manage the agent as a background service.

## Subtasks
1. https://github.com/wazuh/wazuh-agent/issues/130
   - Create a systemd unit file for the Wazuh agent.
   - Handle service installation, enabling, and management (start/stop/restart).
   - Ensure proper logging for service lifecycle events.
2. https://github.com/wazuh/wazuh-agent/issues/131
   - Implement the Wazuh agent as a Windows Service.
   - Ensure service management (start/stop) works as expected via Windows Service Manager.
   - Handle automatic startup on boot.
3. https://github.com/wazuh/wazuh-agent/issues/132
   - Develop a launch daemon configuration for macOS.
   - Implement logic to handle startup, stop, and restart of the agent.
   - Test functionality with `launchctl` to ensure seamless background operation.
4. **Documentation:**
   - Document service installation and management commands for each platform.

**Comment by aritosteles** [comment]
# Update

- **2024/10/17**:
Systemd issue takes precedence over Windows and macOs issues in preparation for MVP presentation. Last minute requests and adjustments.
    - New command line parameter `--config-path` added to wazuh-agent.
    - ConfigurationParser class modified to take a path to the configuration file in the constructor.
    - Agent class modified to take path to configuration file in constructor and pass it along to the configuration parser.
    - UnixDaemon class back to handling PID files and taking care of checking for previous instances and stopping the agent process.
    - Rebased to master and PR up for review and merge.
