### ISSUE TITLE
Create Systemd Service for Linux

### ISSUE THREAD

**Issue by vikman90** [wazuh/wazuh-agent#130]
**Parent Issue:**
- https://github.com/wazuh/wazuh-agent/issues/127

## Description

This subtask focuses on developing a systemd service for the Wazuh agent on Linux platforms. The service must ensure the agent starts automatically at boot, runs in the background, and can be managed via common systemd commands.

## Functional Requirements

- The agent service must be disabled by default.
- Ensure the service can be installed, enabled, started, stopped, and restarted via `systemctl`.
- Properly handle logging of service lifecycle events (start, stop, restart).

## Acceptance Criteria
- The Wazuh agent service is installed and enabled to start at boot.
- Administrators can control the service using standard systemd commands.
- Logs for service events are properly generated and accessible.

**Comment by aritosteles** [comment]
# Update

- **2024/10/08**:
Research on sevice installation with systemd.
Added test for UnixDaemon class.

**Comment by aritosteles** [comment]
##   Linux Options:

--run: Start wazuh-agent in the foreground.
--start: Start wazuh-agent daemon.
--status: Get wazuh-agent daemon status.
--stop: Stop wazuh-agent daemon.
--restart: Restart wazuh-agent daemon.
--register-agent: Register wazuh-agent.
--help: Print help message.
