### ISSUE TITLE
Implement Windows Service for Wazuh Agent

### ISSUE THREAD

**Issue by vikman90** [wazuh/wazuh-agent#131]
**Parent Issue:**
- https://github.com/wazuh/wazuh-agent/issues/127

## Description
This subtask involves implementing the Wazuh agent as a Windows Service. The service should start automatically on boot and allow administrators to manage it using the Windows Service Manager.

## Functional Requirements
- Implement the Wazuh agent as a Windows Service.
- Ensure service can be managed (start, stop, restart) through the Windows Service Manager or via PowerShell.

## Non-Functional Requirements 

- Support Windows Server 2008 R2 and later versions.

## Acceptance Criteria
- The Wazuh agent service starts automatically when the system boots.
- The service can be successfully controlled using Windows Service Manager and PowerShell commands.

**Comment by sdvendramini** [comment]
## 17/10/24
I have begun adding tests for the Windows service functions.

**Comment by sdvendramini** [comment]
Note: Due to the way windows service control manager works. With the changes made, the agent could only be run as a service. Although it supports all the CLI commands indicated in the issue but it could not be run in foreground without being a service.
