### ISSUE TITLE
Linux (RPM) Package Creation

### ISSUE THREAD

**Issue by vikman90** [wazuh/wazuh-agent#133]
**Parent Issue**:
- https://github.com/wazuh/wazuh-agent/issues/128

## Description
This issue focuses on creating an RPM package to facilitate the installation of the Wazuh agent on RHEL-based distributions such as RHEL, CentOS, and Fedora. The package should handle all required dependencies and include pre/post-installation scripts to ensure the service is enabled and running upon installation.

## Functional Requirements
- Develop an RPM spec file compatible with RHEL, CentOS, Fedora, and similar distributions.
- Ensure that all dependencies are correctly handled during installation.
- The Wazuh agent service must be disabled after installation.
- Test the installation and uninstallation workflows to ensure compatibility with RHEL-based systems.

## Acceptance Criteria
- The RPM package is built successfully and integrates with native package managers.
- Installation, uninstallation, and upgrade processes are tested and validated on RHEL-based distributions.

**Comment by mjcr99** [comment]
## Update
**(20/09/2024)** Researching issue requirements and scope, reviewing documentation regarding common practices to properly create packages.
