### ISSUE TITLE
macOS (PKG) Installer Creation

### ISSUE THREAD

**Issue by vikman90** [wazuh/wazuh-agent#135]
**Parent Issue**:
- https://github.com/wazuh/wazuh-agent/issues/128

## Description
This issue involves creating a PKG installer for macOS to enable easy installation of the Wazuh agent. The installer should set up the agent as a launch daemon, configure necessary permissions, and handle post-installation tasks.

## Functional Requirements
- Develop a PKG installer for the Wazuh agent on macOS 14+.
- Ensure the installer sets up the Wazuh agent as a launch daemon.
- Handle file permissions, configuration files, and any required installation scripts.
  
## Acceptance Criteria
- The PKG installer successfully installs the Wazuh agent on macOS.
- The Wazuh agent is configured as a launch daemon and starts automatically after installation.
- The installation, uninstallation, and upgrade processes are tested and verified on macOS 14+.

**Comment by mjcr99** [comment]
## Update:
**(13/11/2024)** Updated code to bring last changes from wazuh/wazuh, working on changing the build process and adding new files.
