### ISSUE TITLE
Implement Daemon Mode for UNIX-based Systems (Linux, macOS)

### ISSUE THREAD

**Issue by vikman90** [wazuh/wazuh-agent#141]
**Parent Issue:**
- https://github.com/wazuh/wazuh-agent/issues/140

## Description

This task focuses on implementing the daemon (background service) mode of the Wazuh agent specifically for UNIX-based systems, including Linux and macOS. The agent will need to support being run as a background process, with appropriate management of process lifecycle and system integrations.

## Functional Requirements

1. Implement process forking to run the Wazuh agent as a daemon.
2. Create a logging mechanism that outputs to standard system logs (e.g., syslog).
3. Ensure proper handling of the background process, including process ID (PID) management.
4. The agent should respond to the CLI commands:
   - `wazuh-agent start` (starts the agent in daemon mode)
   - `wazuh-agent status` (checks if the agent is running)
   - `wazuh-agent stop` (stops the daemon process)
  
## Non-Functional Requirements

- The solution must adhere to best practices for daemon creation, including proper file descriptor handling and signal management.
- Ensure robust error handling and log any failures in the appropriate system logs.
  
## Acceptance Criteria

1. The agent runs as a background service on Linux and macOS.
2. The agent correctly responds to `start`, `stop`, and `status` commands.
3. Logs are appropriately stored in syslog for both Linux and macOS.

**Comment by aritosteles** [comment]
# Update

- **2024/09/17**:
Understanding issue requirements and doing research on daemon implementation.
