### ISSUE TITLE
Implement Daemon Mode for Windows

### ISSUE THREAD

**Issue by vikman90** [wazuh/wazuh-agent#142]
**Parent Issue:**
- https://github.com/wazuh/wazuh-agent/issues/140

## Description

This task focuses on implementing the daemon (background service) mode of the Wazuh agent for Windows systems. The agent will need to function as a Windows service that can be managed using the standard Windows Service Manager interface.

## Functional Requirements

1. Implement the Wazuh agent as a Windows service using Windows Service API.
2. Create a logging mechanism that writes to the Windows Event Viewer.
3. Integrate the agent with the Windows Service Manager, enabling the following CLI commands:
   - `wazuh-agent start` (starts the agent service)
   - `wazuh-agent status` (checks if the agent is running as a service)
   - `wazuh-agent stop` (stops the agent service)
4. The agent should handle Windows service events and control signals gracefully.

## Non-Functional Requirements

- The service must be properly registered with the Windows Service Manager and adhere to Windows service best practices.
- Error handling and logs should be properly written to the Windows Event Viewer.

## Acceptance Criteria

1. The agent correctly responds to `start`, `stop`, and `status` commands.
2. Logs are appropriately stored in the Windows Event Viewer.

**Comment by sdvendramini** [comment]
## 18/09/2024
Understanding issue requirements and doing research on windows services implementation. Looked at the old wazuh-agent windows service code. Synch with team mates to develop the parts this issue and the Unix daemon issue have in common.
