### ISSUE TITLE
Integrate the Command Handler with the Module Manager

### ISSUE THREAD

**Issue by TomasTurina** [wazuh/wazuh-agent#146]
**Parent issue:**
- https://github.com/wazuh/wazuh/issues/22887

## Description

After the development of the new [Command Handler](https://github.com/wazuh/wazuh-agent/issues/83), it is necessary to integrate it with the Module Manager so that modules can execute commands and report their feedback.

## Considerations

- All commands should be executed in the order they are created.
- The Command Handler should use the Module Manager to find a given module and send the command.
- A coroutine should be created for each command to wait for the command to be executed and for the module to respond.
- The command response should be stored in the Queue so that the result is communicated to the manager.
- The command response should be persisted in the command store.
- If no response is received after a time, the coroutine should consider marking the command status as timeout.
  - Result should also be stored in the Queue.

After the implementation is complete, we also need to add some UT to test the entire execution flow of a command.

**Comment by jr0me** [comment]
### Update

Started looking into the issue and its requirements. Also looking at the current state of the involved components' code and the branch enhancement/17-migrate-syscollector-to-inventory-at-new-agent.

**Comment by jr0me** [comment]
### Update

Created branch and linked it to this issue. Started looking into the `CommandHandler`, `CommandStore` and `ModuleWrapper` to come up with a solution.

**Comment by jr0me** [comment]
### Update

Implemented first attempt to process a command, fetching its corresponding module and passing to it the command b4dc05b0c357c08ca16f8449efa0a554f401c325

Now it's necessary to come up with a non blocking mechanism to execute commands.

**Comment by jr0me** [comment]
### Update

Implemented first approach with coroutines. The functions (in modules, module wrapper, etc) that execute the commands needed to return `awaitables` among other changes. Testing with the new server comms mvp.

**Comment by jr0me** [comment]
### Update

Defined an initial format for the stateful messages created by command executions.

```json
{
  "data":
  {
    "id": str,
    "error": int,
    "message": str
  },
  "module": str
}
```

Further improvements to the coroutines approach used so far. There's a dependency between the ModularManager, ModuleWrapper, Inventory, Command, CommandStore, CommandHandler that needs further iterations to improve.

**Comment by jr0me** [comment]
### Update

Created draft PR. Timeout implementation is currently missing, as well as the insurance of execution order, since at the moment only one sequential execution at the time is allowed.

**Comment by jr0me** [comment]
### Update

First PR merged, now looking into adding a timeout mechanism to dispatched commands, and to allow multiple commands to be dispatched simultaneously.

**Comment by jr0me** [comment]
### Update

Debugging the timeout mechanism implemented. Working on branch https://github.com/wazuh/wazuh-agent/tree/enhancement/146-simultaneous-command-dispatch-with-timeout

**Comment by jr0me** [comment]
### Update

Created PR after implementing and testing the dispatch of multiple commands.
