### ISSUE TITLE
Mark in-progress commands as not executed after restarting an agent

### ISSUE THREAD

**Issue by TomasTurina** [wazuh/wazuh-agent#154]
## Description

As part of the development of the new agent, a [command handler](https://github.com/wazuh/wazuh-agent/issues/83) was introduced to handle the execution of commands received from the server.

Since an agent can stop or restart its execution at any time, this can happen while there are commands in progress that have not yet reported their result. Since the manager needs to know the result of each command, the command handler must check if there are any commands in progress at startup and report their result to the manager. For these cases, the commands must be marked as "agent stopped during execution" and this will be the reported result.

## Considerations

- The command handler should check for in-progress commands upon startup.
- This will be a one-time check.
- If in-progress commands are found, their status and result will be updated in the command store to reflect that the agent stopped during execution.
- The result should be added to the queue to inform the manager, which will be waiting for this response.
- If specified, the command should be removed from the command store after the result is queued.

**Comment by sdvendramini** [comment]
### 28/11/2024
I've started working on the issue, analyzing the existing code and considering possible changes needed to achieve the issue's goal.

**Comment by sdvendramini** [comment]
As agreed with @TomasTurina @GGP1 @AlexRuiz7 , the commands will have a new field called `document_id`, which will act as their unique identifier. They will be structured as follows:

```
  "commands": [
    {
      "document_id" : "SuyTlZIBRVsFsWNvvx6f",
      "request_id": "aeyvlZIBRVsFNWNvvj6f",
      "order_id": "auyvlZIBRVsFNWNvvj6f",
      "source": "Users/Services",
      "user": "Management API",
      "target": {
        "id": "0a96a0ab-5bef-415c-bb3c-ea3e294215a0",
        "type": "agent"
      },
      "action": {
        "name": "restart",
        "version": "v5.0.0",
        "args": []
      },
      "timeout": 100,
      "status": "pending"
    }
]
```

Stateful events reporting the command results will look like this:

```
{"module": "command", "id": "SuyTlZIBRVsFsWNvvx6f", "operation": "update"}
{"command":{"result":{"code":4,"message":"Agent stopped during execution"}}}
{"module": "command", "id": "1", "operation": "update"}
{"command":{"result":{"code":0,"message":"Success"}}}
```
