### ISSUE TITLE
Implement Queue Component

### ISSUE THREAD

**Issue by cborla** [wazuh/wazuh-agent#16]
**Parent issue:**
- #17

## Description
Develop and integrate the _Queue_ component into the agent framework using C++. This component will handle the messages generated by the Inventory module and other modules.

## Tasks
1. Design the architecture of the _Queue_ component.
2. Develop the _Queue_ component.
3. Integrate the _Queue_ component with the agent framework.
4. Test the _Queue_ component to ensure proper functionality.

## Implementation restrictions
- **Multiple instances**: Sort stateful, stateless and commands messages. Will preferably be implemented without multithreading, using coroutines or similar. (use C++20)
- **Storage**: Output from FIM, Logcollector, Inventory, etc, will end up in this component.
- **Persistence**: Whatever is in this memory must remain even if the agent is disconnected or shut down.
- **Limitation**: We will do it at the input. If the limit is reached, we will leave the Insert operation blocked until there is space.
- **Reading**: The consumer (connection to the server) will be able to take up to N messages from this queue, depending on the type (stateless/stateful/command). there are several instances. They are not deleted from the queue, it is a simple poll.
- **Management**: when the client has sent the messages and has the ACK, then it will remove them from the queue.

## Dependencies
None

**Comment by LucioDonda** [comment]
## Base ideas

* Should be thread-safe: If multiple threads are using it, the events stored should remain, and it shouldn't copy the whole queue in each case. If we can't be sure how this will be instantiated then the options are as a singleton (maybe a little problematic with tests), with dependency injection or using factory methods.
* Data persistence: After each push/pop the changes should also impact in a persistence mechanism that allows the queue to recover it's previous state after a shutdown, reset or unexpected close.
  * Init methods should recover this state if some data is present.
  * This should be an interface that allows using several libraries or simply plain text. (sqlite and rocksdb should be checked).
  * This data shouldn't be modifiable from the outside (checksum ?).
*configurations should be taken from toml.
  * some fields can be: queue_max_size, EPS_limit (?)
* Should we handle the removal of the messages internally (after the ACK) or just by making public the pop method it's enough.
* Allow to pushing / popping / getting of N messages.
* Do the other teams using the queue have additional requirements?

## Development process:
* Sequence / Communication / Class diagrams if needed.
* TDD.
* Defined Format as in the [coding style](https://github.com/wazuh/wazuh/wiki/Coding-style-guide-%28C-plus-plus%29#exceptions-and-errors)
* benchmarking with options
* Documentation (class, methods, examples and basic usage).

## Nice to have:
* Use coroutines (c++20). Block push methods when busy and return control to the caller when done.

**Comment by LucioDonda** [comment]
### class diagram (WIP)

```mermaid
classDiagram
    class MessageType {
        +STATE-LESS
        +STATE-FULL
        +COMMAND
    }
    class Event {
        -type: MessageType
        -data: x-json
        +Event(type: MessageType, data: x-json)
    }
    class MultiTypeQueue {
        -queues: vector[queue[Event]]
        -mtx: mutex
        -cv: condition_variable
        -max_items: int
        +MultiTypeQueue(size: int)
        +push(event: Event) // Blocking if full -> persist
        +getLastEvent(type: MessageType): Event // For procesing
        +popLastEvent(type: MessageType) // After ACK
        +updateLast(event: Event) // Reset command -> double check
        +isEmptyByQueue(type: MessageType): boolean
    }

```

**Comment by cborla** [comment]
# Queue persistence options

Some of the options for persisting messages in the queue are described below:

### Disk Storage

- Use files to store the queue messages. You can write the messages in JSON format to a file as soon as they are added to the queue and delete them from the file once they are processed.

### Embedded Database

- Use an embedded database like SQLite. SQLite is lightweight and easy to use, allowing you to store messages persistently in a database file.
  - **Benefits:**
    - Atomic transactions, ensuring data integrity.
    - Easy recovery of unprocessed data upon restarting the application.

### Persistence Libraries and Frameworks

- **RocksDB:** An embedded storage library optimized for fast read/write operations. RocksDB can be useful for handling a high-performance persistent queue.
- **Boost.Serialization:** Can be used to serialize JSON messages and save them to disk.
- **Redis:** If you are open to a client-server approach, Redis can be an option. Although not embedded, Redis offers persistence through snapshots and Append-Only File (AOF) logs.

## Selected Option
According to tests and analysis performed by the @TomasTurina team (link coming soon), we chose to continue the implementation with the Embedded Database (SQLite) database option.

**Comment by cborla** [comment]
# Database structure

To determine the best option in terms of efficiency and speed, we need to consider factors such as query complexity, concurrency, and ease of maintenance. Here are the options analyzed

## Options 

### Option 1: A single database with a single table, differentiating event types in a column

- Advantages:
Simplicity in administration: only one table and one database to manage.
Less overhead in handling multiple connections to different databases.

- Disadvantages:
Potentially slower queries if the table grows large since each query will have to filter by event type.
Less isolation between event types, which can lead to contention if there is high concurrency of read/write operations.

- Table structure:
``` sql
CREATE TABLE events (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    type TEXT NOT NULL,
    message TEXT NOT NULL
);
```

### Option 2: A single database with a table for each event type
- Advantages:
Faster queries as each table contains only one event type.
Better isolation of event types, which can reduce contention.

- Disadvantages:
More complexity in administration since you have to manage multiple tables.
The application logic is slightly more complex to handle multiple tables.

- Table structure:
``` sql 
CREATE TABLE commands (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    message TEXT NOT NULL
);

CREATE TABLE stateful_messages (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    message TEXT NOT NULL
);

CREATE TABLE stateless_messages (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    message TEXT NOT NULL
);

```

### Option 3: Three databases, one for each event type

- Advantages:
Maximum isolation between event types, which can be beneficial in systems with high concurrency and high data volume.
Databases can be located on different devices or partitions, improving performance if the file system allows it.

- Disadvantages:
Greater complexity in administration and maintenance of multiple databases.
Overhead in handling multiple connections to different databases.

- Database structure:
Each database would have a table similar to the structure in Option 2.

## Recommendation
Option 2 (a single database with a table for each event type) is usually the best option in terms of balancing efficiency, speed, and ease of maintenance:

- Faster queries by working with smaller, specialized tables.
- Better isolation between event types, which can reduce contention and improve performance in systems with high concurrency.
- Less administrative complexity compared to managing multiple databases, while maintaining logical separation of data.

## Test (wip)

## Implementation (wip)

**Comment by LucioDonda** [comment]
## Coroutines usage check:

In order to check if coroutines are a positive approach for solving this we are comparing a base case without them and one with them in order to check which pros and cons have:

### Without Coroutines:

<details><summary>Details</summary>
<p>

```c++

#include <iostream>
#include <fstream>
#include <thread>
#include <mutex>
#include <condition_variable>
#include <vector>
#include <atomic>
#include <filesystem>

class PersistedStorage {
public:
    PersistedStorage(const std::string& filename) : filename(filename) {
        std::ofstream ofs(filename, std::ios::out | std::ios::trunc);
        ofs.close();
    }

    void push(int item) {
        std::ofstream ofs(filename, std::ios::out | std::ios::app);
        ofs << item << std::endl;
        ofs.close();
    }

    std::vector<std::string> popN(size_t n) {
        std::vector<std::string> all_lines;
        std::ifstream ifs(filename);
        std::string line;

        // Read all lines from the file
        while (std::getline(ifs, line)) {
            all_lines.push_back(line);
        }
        ifs.close();

        // Check if n is greater than the number of lines in the file
        if (n > all_lines.size()) {
            n = all_lines.size();
        }

        // Create a vector for the lines to return and remove
        std::vector<std::string> last_n_lines(all_lines.begin(), all_lines.begin() + n);
        all_lines.erase(all_lines.begin(), all_lines.begin() + n);

        // Write the remaining lines back to the file
        std::ofstream ofs(filename, std::ios::out | std::ios::trunc);
        for (const auto& remaining_line : all_lines) {
            ofs << remaining_line << std::endl;
        }
        ofs.close();

        return last_n_lines;
    }

    int pop() {
        auto vectorResult = popN(1); 
        return atoi(vectorResult.at(0).c_str());
    }

    bool empty() {
        std::ifstream ifs(filename);
        return ifs.peek() == std::ifstream::traits_type::eof();
    }

    int front() {
        std::lock_guard<std::mutex> lock(file_mtx);
        std::ifstream ifs(filename);
        std::string line;
        std::vector<int> items;
        while (std::getline(ifs, line)) {
            if (!line.empty()) {
                items.push_back(std::stoi(line));
            }
        }
        ifs.close();

        if (items.empty()) {
            return -1; // or throw an exception if preferred
        }

        return items.front();
    }

    size_t size() {
        std::lock_guard<std::mutex> lock(file_mtx);
        std::ifstream ifs(filename);
        size_t count = 0;
        std::string line;
        while (std::getline(ifs, line)) {
            if (!line.empty()) {
                count++;
            }
        }
        return count;
    }

private:
    std::string filename;
    std::mutex file_mtx;
};

class ProdConsQueue {
public:
    ProdConsQueue(size_t max_size, const std::string& filename)
        : storage(filename), max_size(max_size), done(false) {}

    void produce(int item) {
        std::unique_lock<std::mutex> lock(mtx);
        cv_produce.wait(lock, [this]() { return storage.size() < max_size; });
        storage.push(item);
        std::cout << "Produced: " << item << std::endl;
        cv_consume.notify_one();
    }

    bool consume(int& item) {
        std::unique_lock<std::mutex> lock(mtx);
        cv_consume.wait(lock, [this]() { return !storage.empty() || done; });
        if (!storage.empty()) {
            item = storage.pop();
            cv_produce.notify_one();
            return true;
        }
        return false;
    }

    void finish() {
        std::unique_lock<std::mutex> lock(mtx);
        done = true;
        cv_consume.notify_all();
    }

    void producer(int start, int count) {
        for (int i = 0; i < count; ++i) {
            produce(start + i);
            std::this_thread::sleep_for(std::chrono::milliseconds(100)); // Simulate work
        }
    }

    void consumer(int count) {
        int item;
        for (int i = 0; i < count; ++i) {
            if (consume(item)) {
                std::cout << "\tConsumed: " << item << std::endl;
                std::this_thread::sleep_for(std::chrono::milliseconds(100)); // Simulate work
            }
        }
    }

private:
    PersistedStorage storage;
    std::mutex mtx;
    std::condition_variable cv_produce;
    std::condition_variable cv_consume;
    size_t max_size;
    std::atomic<bool> done;
};

void run_example() {
    const std::string filename = "storage.txt";
    ProdConsQueue queue(5, filename); // Small max size for demonstration

    std::thread producer_thread1(&ProdConsQueue::producer, &queue, 0, 5);
    std::thread consumer_thread1(&ProdConsQueue::consumer, &queue, 2);

    producer_thread1.join();
    consumer_thread1.join();

    std::thread producer_thread2(&ProdConsQueue::producer, &queue, 5, 5);
    std::thread consumer_thread2(&ProdConsQueue::consumer, &queue, 8);
    
    producer_thread2.join();

    using namespace std::chrono_literals;
    std::cout << "a little pause till I can consume the rest" << std::endl;
    std::this_thread::sleep_for(1000ms);
    
    consumer_thread2.join();

    std::thread producer_thread3(&ProdConsQueue::producer, &queue, 10, 3);
    std::thread consumer_thread3(&ProdConsQueue::consumer, &queue, 3);

    producer_thread3.join();
    consumer_thread3.join();

    queue.finish();
}

int main() {
    run_example();
    return 0;
}


``` 

</p>
</details> 

### With Coroutines (WIP):

<details><summary>Details</summary>
<p>

```c++


``` 

</p>
</details>

**Comment by LucioDonda** [comment]
## Update (05/07/2024)

I made some changes on the code: Added `tests` directory. Improve code style with clang. And improved the multithreading behavior (one lock per queue). Everything in https://github.com/wazuh/wazuh-agent/pull/28/commits/26aeb394c00694d1dee5009562b42602242e11e7

**Comment by LucioDonda** [comment]
## Update (08/07/2024)

I started the analysis for overloading the getMessage method with boost coroutines but didn't achieve much because I had to switch to another issue.

**Comment by LucioDonda** [comment]
## Update (10/07/2024)

Added additional tests. code corrections (using c++20 features like contains) and some functions for json handling. Pending finishing with them in order to correctly check when the coroutine method is done that it works without any additional impact.

**Comment by cborla** [comment]
## Update (10/07/2024)

Completing stage 1 of persistence, this first version will be implemented by interface.

Pending:
- Upload the changes to the `16-implement-queue-component branch`.
- Integrate the persistence module with the queue.

<details><summary>Persistence.h</summary>

``` c++
#ifndef PERSISTENCE_H
#define PERSISTENCE_H

#include <nlohmann/json.hpp>
#include <vector>

using json = nlohmann::json;

enum MessageType {
    STATE_LESS,
    STATE_FULL,
    COMMAND
};

class Persistence {
public:
    virtual ~Persistence() = default;
    virtual void Store(MessageType type, const json& message) = 0;
    virtual json Retrieve(MessageType type, int id) = 0;
    virtual json RetrieveMultiple(MessageType type, int n) = 0;
    virtual void Remove(MessageType type, int id) = 0;
    virtual void RemoveMultiple(MessageType type, int n) = 0;
};

#endif // PERSISTENCE_H

```

</details>


<details><summary>SQLiteStorage.h</summary>

``` c++
#ifndef SQLITE_STORAGE_H
#define SQLITE_STORAGE_H

#include "Persistence.h"
#include <sqlite3.h>
#include <string>
#include <mutex>
#include <unordered_map>

class SQLiteStorage : public Persistence {
public:
    SQLiteStorage(const std::string& dbName);
    ~SQLiteStorage() override;

    void Store(MessageType type, const json& message) override;
    json Retrieve(MessageType type, int id) override;
    json RetrieveMultiple(MessageType type, int n) override;
    void Remove(MessageType type, int id) override;
    void RemoveMultiple(MessageType type, int n) override;

    void OpenDB();
    void CloseDB();

private:
    void InitializeTable(const std::string& tableName);

    std::string dbName;
    sqlite3* db;
    std::unordered_map<MessageType, std::string> tableNames;
    std::mutex mtx;
};

#endif // SQLITE_STORAGE_H


```

</details>

<details><summary>SQLiteStorage.cpp</summary>

``` c++

#include "SQLiteStorage.h"
#include <iostream>

SQLiteStorage::SQLiteStorage(const std::string& dbName) : dbName(dbName) {
    tableNames[STATE_LESS] = "state_less";
    tableNames[STATE_FULL] = "state_full";
    tableNames[COMMAND] = "command";

    OpenDB();
    for (const auto& pair : tableNames) {
        InitializeTable(pair.second);
    }
    CloseDB();
}

SQLiteStorage::~SQLiteStorage() {
    // Destructor vacío ya que la base de datos se cerrará después de cada operación
}

void SQLiteStorage::OpenDB() {
    sqlite3_open(dbName.c_str(), &db);
}

void SQLiteStorage::CloseDB() {
    sqlite3_close(db);
}

void SQLiteStorage::InitializeTable(const std::string& tableName) {
    std::string createTableQuery = "CREATE TABLE IF NOT EXISTS " + tableName + " ("
                                   "id INTEGER PRIMARY KEY AUTOINCREMENT, "
                                   "message TEXT NOT NULL);";
    sqlite3_exec(db, createTableQuery.c_str(), 0, 0, 0);
}

void SQLiteStorage::Store(MessageType type, const json& message) {
    std::lock_guard<std::mutex> lock(mtx);
    OpenDB();

    std::string tableName = tableNames[type];
    std::string insertQuery = "INSERT INTO " + tableName + " (message) VALUES (?);";
    sqlite3_stmt* stmt;
    sqlite3_prepare_v2(db, insertQuery.c_str(), -1, &stmt, 0);
    std::string messageStr = message.dump();
    sqlite3_bind_text(stmt, 1, messageStr.c_str(), -1, SQLITE_TRANSIENT);
    sqlite3_step(stmt);
    sqlite3_finalize(stmt);

    CloseDB();
}

json SQLiteStorage::Retrieve(MessageType type, int id) {
    std::lock_guard<std::mutex> lock(mtx);
    OpenDB();

    std::string tableName = tableNames[type];
    std::string selectQuery = "SELECT message FROM " + tableName + " WHERE id = ?;";
    sqlite3_stmt* stmt;
    sqlite3_prepare_v2(db, selectQuery.c_str(), -1, &stmt, 0);
    sqlite3_bind_int(stmt, 1, id);
    json message;
    if (sqlite3_step(stmt) == SQLITE_ROW) {
        std::string messageStr = reinterpret_cast<const char*>(sqlite3_column_text(stmt, 0));
        message = json::parse(messageStr);
    } else {
        message = nullptr;
    }
    sqlite3_finalize(stmt);

    CloseDB();
    return message;
}

json SQLiteStorage::RetrieveMultiple(MessageType type, int n) {
    std::lock_guard<std::mutex> lock(mtx);
    OpenDB();

    std::string tableName = tableNames[type];
    std::string selectQuery = "SELECT message FROM " + tableName + " ORDER BY id DESC LIMIT ?;";
    sqlite3_stmt* stmt;
    sqlite3_prepare_v2(db, selectQuery.c_str(), -1, &stmt, 0);
    sqlite3_bind_int(stmt, 1, n);
    json messages = json::array();
    while (sqlite3_step(stmt) == SQLITE_ROW) {
        std::string messageStr = reinterpret_cast<const char*>(sqlite3_column_text(stmt, 0));
        messages.push_back(json::parse(messageStr));
    }
    sqlite3_finalize(stmt);
    std::reverse(messages.begin(), messages.end());

    CloseDB();
    return messages;
}

void SQLiteStorage::Remove(MessageType type, int id) {
    std::lock_guard<std::mutex> lock(mtx);
    OpenDB();

    std::string tableName = tableNames[type];
    std::string deleteQuery = "DELETE FROM " + tableName + " WHERE id = ?;";
    sqlite3_stmt* stmt;
    sqlite3_prepare_v2(db, deleteQuery.c_str(), -1, &stmt, 0);
    sqlite3_bind_int(stmt, 1, id);
    sqlite3_step(stmt);
    sqlite3_finalize(stmt);

    CloseDB();
}

void SQLiteStorage::RemoveMultiple(MessageType type, int n) {
    std::lock_guard<std::mutex> lock(mtx);
    OpenDB();

    std::string tableName = tableNames[type];
    std::string deleteQuery = "DELETE FROM " + tableName + " WHERE id IN (SELECT id FROM " + tableName + " ORDER BY id DESC LIMIT ?);";
    sqlite3_stmt* stmt;
    sqlite3_prepare_v2(db, deleteQuery.c_str(), -1, &stmt, 0);
    sqlite3_bind_int(stmt, 1, n);
    sqlite3_step(stmt);
    sqlite3_finalize(stmt);

    CloseDB();
}

```

</details>

**Comment by cborla** [comment]
## Update (11/07/2024)

Updating persistance, this first version will be implemented by interface.
- Adapting the persistence code to the queue.
- Added GetElementCount function.
- Adjustment of variables and functions.
- The name of the table is assigned at the time of instantiation of the calss.


``` mermaid
classDiagram
    class Persistence {
        <<interface>>
        +~Persistence()
        +~Store(json message)
        +~json Retrieve(int id)
        +~json RetrieveMultiple(int n)
        +~void Remove(int id)
        +~void RemoveMultiple(int n)
        +~int GetElementCount()
    }

    class SQLiteStorage {
        +SQLiteStorage(string dbName, string tableName)
        +~Store(json message)
        +~json Retrieve(int id)
        +~json RetrieveMultiple(int n)
        +~void Remove(int id)
        +~void RemoveMultiple(int n)
        +~int GetElementCount()
        -InitializeTable(string tableName)
        -string m_dbName
        -string m_tableName
        -sqlite3* m_db
        -mutex m_mtx
    }

    Persistence <|-- SQLiteStorage

```

**Comment by LucioDonda** [comment]
## Update (11/07/2024)

Improoving test coverage and working on merge with persistence implementation.

**Comment by LucioDonda** [comment]
## Update (12/07/2024)

* Integration with sqlite3 persistence implementation.
* Adding file implementation.
* Allowing the use of both through a factory class
* Additional tests and code cleanup.

**Comment by LucioDonda** [comment]
## Update (15/07/2024)

* Adding tests.
* Fixing some multithreading issues.
* Defining some key steps for persistence side.

**Comment by cborla** [comment]
## Update (16/07/2024)

- Moving forward with the change of library, to a c++ library.
  - We moved from sqlite3 to [SQLiteCpp](https://github.com/SRombauts/SQLiteCpp).
- Change of mutex handling according to the new library, and method of use of the base, we must keep it constantly open.

**Comment by LucioDonda** [comment]
## Update (16/07/2024)

* Implementing Methods for N messages
* Json array handling
* adding tests

**Comment by LucioDonda** [comment]
## Update (17/07/2024)

* Multithreading corrections (In progress)
* Code cleaning
* Reworking on items count methods

**Comment by cborla** [comment]
## Update (17/07/2024)

* Rebase with updated code, conflicts resolved.
* Adapt store method to support vectors.
* Code cleaning.
* Exception Handling has been added.

**Comment by cborla** [comment]
## Update (18/07/2024)

* Appropriate Transactions: Handle transactions in a way that ensures data integrity and avoids database deadlocks.
* (WIP) Shared Connections: Use a shared connection for all SQLiteStorage instances.

**Comment by LucioDonda** [comment]
## Update (19/07/2024)

* Cleaning locks and fixing multithreaded issues
* Adding timeout for pushing method
* Code cleaning and separation of headers and cpp in queue
* Building as library and not as binary
* pending push with stop_token

**Comment by cborla** [comment]
## Update (19/07/2024)

* (WIP) Shared Connections: Use a shared connection for all SQLiteStorage instances.

**Comment by LucioDonda** [comment]
## Update (22/07/2024)

* Rebase with master.
* Using vcpkg through json
* clang corrections.

**Comment by cborla** [comment]
## Update (22/07/2024)

* Shared Connections: Use a shared connection for all SQLiteStorage instances.
* sqlitestorage UT refactor.

**Comment by LucioDonda** [comment]
## Update (26/07/2024)

* Solving multithreading issues on queue.
* Analysis on possible sqlitecpp multithreading approaches
* Rework on use of transactions. Pending push.

**Comment by LucioDonda** [comment]
## Update (29/07/2024)

* Pushing previous changes and clang to other files.
* Analysis of time spent on each phase of the test for several messages cases.
* All sqlite storage tests passing. multithreading solved at that level.
* Working on a solution of issue in mutithread with different queues scenario.

**Comment by LucioDonda** [comment]
## Update (30/07/2024)

* Multiple uses of DB.
  * connection pool approach discarded.
  * singleton approach almost discarded. -> looking for alternatives that won't broke the independence between queue and persistence implementation.

**Comment by LucioDonda** [comment]
## Update (31/07/2024)

* Pushed 3 files approach, all test passing.
* Working on changes for single db file and 3 tables.
* Pending comparison between both on time and size required.

**Comment by LucioDonda** [comment]
## Update (01/08/2024)

* pushed single DB file approach, all test passing
* Creating and running tests for comparison.
* Pending rerunning on 3 files

### Results of tests:

Single DB approach:

| times | Filling all Queues [uS] | Filling single Queue [uS] | Pulling [uS] | Reading/Pulling [uS] | Size [kB] |
|--------|--------|--------|--------|--------|--------|
| **100** messages / avg per message |  351381 / 3513 |117127 / 1171 | 276662 / 2766 | 242754 / 2427 | 24,5 |
| **1K** messages / avg per message | 1992076 / 1991 | 664025 / 663 | 1302967 / 1302 | 1755765 / 1755 |151,5 |
| **10K** messages / avg per message | 15126575 / 1512| 5042191 / 503 |13415571 / 1341 | 18510016 / 1850 |1314,8 |

**Comment by LucioDonda** [comment]
## Update (02/08/2024)

* Finished previous comparison.
  * Decided for the single DB approach.
* Changes on exceptions handling.
* Working on module column addition, pending corrections and push.

**Comment by LucioDonda** [comment]
## Update (05/08/2024)

* Working on module data:
  * Should be mandatory? can a message have an empty module?
  * fetches are allowed with or without it.
  * fetching N messages will return an object of Message type with:
   type one of:     STATELESS,    STATEFUL,  COMMAND
   moduleName : "some string" ,
   and data:
   
```
   [
    {
        "data": {
            "data": "value"
        },
        "module": "someModule1"
    },
    {
        "data": {
            "data": "value"
        },
        "module": ""
    },
    ... ,
    {
        "data": {
            "data": "value"
        },
        "module": "someOtherModule"
    }
]
```
Still WIP

**Comment by LucioDonda** [comment]
## Update (06/08/2024)

* rebase with latest in master.
* First implementation with module data uploaded.
  * Pending tests and improvements in module field additions

**Comment by LucioDonda** [comment]
## Update (07/08/2024)

* Module functionality for other methods.
  * tests addition.

**Comment by LucioDonda** [comment]
## Update (08/08/2024)

* Module functionality for other methods.
  * Addition to the rest of the queue methods
* Return number of rows deleted or inserted with tests
* Additional test and removing duplicated ones.

**Comment by LucioDonda** [comment]
## Update (09/08/2024)

* Function renaming for clearer use.
* Awaitable approach using boost asio.
  * implemented on getting and pushing methods: both needed because they can be locked on full or empty queues. pop only should be used after getting a message and receiving an ack. 
  * Base tests. Pending some further checks.
  * N messages should e awaitables too.

**Comment by LucioDonda** [comment]
## Update (12/08/2024)

* Changes on awaitable methods for N messages.
* Changes for correct fifo order on getter method.
* Additional tests and code cleanup.
[PR](https://github.com/wazuh/wazuh-agent/pull/28) Ready for review
