### ISSUE TITLE
The non-UTF8 character check excludes valid UTF8 characters

### ISSUE THREAD

**Issue by zbalkan** [wazuh/wazuh-agent#179]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.7.5> | Wazuh agent | Agent | N/A | N/A |

# Summary

This is a continuation of issue https://github.com/wazuh/wazuh/issues/23354, about the fix PR https://github.com/wazuh/wazuh/pull/23543.

After the fix, the agent, unfortunately, does an ASCII character check instead of UTF-8 check. Therefore, when there are characters like Ü, ü, Õ, õ, Ö, ö, Ä, ä, Ş, ş, Ç, ç, etc., in the path of the files, the FIM ignores them as not valid UTF-8 while they are valid UTF-8 characters. These are valid UTF-8 characters and I believe the nlohmann library would accept these as well.

**Comment by MarcelKemp** [comment]
@zbalkan could you cherry-pick the PR commits from `4.10.2`, to this repository? That way, we will also merge it here so that the fix is in `5.X`.
- https://github.com/wazuh/wazuh/pull/26289

Thanks in advance!

**Comment by zbalkan** [comment]
Hi @MarcelKemp ,

I did it last week. The PR is on https://github.com/wazuh/wazuh-agent/pull/180.

**Comment by MarcelKemp** [comment]
The changes to the integration tests are missing. If you could add them, I would appreciate it. 
The new path is in the FIM module itself:
- https://github.com/wazuh/wazuh-agent/tree/master/src/modules/fim/tests/integration

**Comment by zbalkan** [comment]
Since my PR was relatively old and rebase or cherry-picking may not be the best for me, I created a separate commit instead.
