### ISSUE TITLE
Change package scaffolding for wazuh-agent

### ISSUE THREAD

**Issue by vikman90** [wazuh/wazuh-agent#242]
We need to set the following destination folders in the Linux package:

- `/usr/share/wazuh-agent/bin`
   Executable files.
- `/usr/share/wazuh-agent/lib`
   Internal libraries (if needed).
- `/etc/wazuh-agent/ `
   Configuration file (_wazuh-agent.yml_).
- `/var/lib/wazuh-agent/ `
   Databases and files which may change.

Apply the changes above for the packages:
- [ ] DEB
- [ ] RPM

**Comment by MarcelKemp** [comment]
## Update
Changes applied in the following branch: `change/242-package-scaffolding`.
Problem: It's causing crashes because the binary can't find the libraries (`libdbsync`), due to the path change. 
On Monday I will continue and discuss the possibilities.
