### ISSUE TITLE
Let the agent accept a server address as URL

### ISSUE THREAD

**Issue by vikman90** [wazuh/wazuh-agent#243]
**Parent Issue:** https://github.com/wazuh/wazuh-agent/issues/241

Replace the `manager_ip` setting with `server_url`. This setting shall accept a URL:

- Accept both HTTP and HTTPS.
- Accept IP addresses, names, and FQDNs.

## Example

```yaml
server_url:       https://server.wazuh.com.test:27000
registration_url: https://server.wazuh.com.test:55000
```

**Comment by vikman90** [comment]
## Issue Update

### October 31
- PR #258
- Applying requested changes.

**Comment by aritosteles** [comment]
# Update

- Config settings renamed to server_url and registration_url. Port and UseHttps settings removed. All classes, functions and tests involved were refactored.
- Added boost::urls for url parsing and validation.
     - Parsing and validation done in HttpRequestParams, Communicator and AgentRegistration classes.
     - In case of ill-formated urls in config file a log entry is created, no crash or exceptions thrown. More thorough validation of config settings is in order. 
- HttpRequestParams class moved to its own hpp and cpp files.
-Added flag `--output-on-failure` to ctest execution to help debug failing tests.

PR is on final review
