### ISSUE TITLE
Let the agent's CLI key option be optional

### ISSUE THREAD

**Issue by vikman90** [wazuh/wazuh-agent#246]
**Parent Issue:** https://github.com/wazuh/wazuh-agent/issues/241

Currently, option `--key` is mandatory when trying to register the agent.

Let this parameter be optional. Should it not be defined, create a random one.

**Comment by sdvendramini** [comment]
## 30/10/2024
I was resolving [PR](https://github.com/wazuh/wazuh-agent/pull/252) comments and adding tests and documentation.
