### ISSUE TITLE
Attach agent information in communication to the server

### ISSUE THREAD

**Issue by vikman90** [wazuh/wazuh-agent#256]
**Parent Issue:** https://github.com/wazuh/wazuh-agent/issues/241

When the agent registers, it must send information about itself to the server:
- IP address
- Operating system
- Agent version

This information must also be attached to the metadata headers in stateful and stateless messages.

**Comment by TomasTurina** [comment]
## Update

Working on the solution. The following information will be included:

`agent_data`:
- IP
- OS
- Version

`group_data`:
- group1,group2,…

**Comment by TomasTurina** [comment]
## Update

Working on new definition (new message structure). The structure of the registration request is still missing.

**Comment by TomasTurina** [comment]
# Messages format

## Registration request

- API: Server Management

### Authentication:

- Endpoint: `/security/user/authenticate`

- Method: POST

- Headers:
  - Authorization: Basic `base64(user:pass)`

- Body: _empty_

### Registration

- Endpoint: `/agents`

- Method: POST

- Headers:
  - Authorization: Bearer `token`

- Body: _json_
  - os: OS
  - platform: PLATFORM
  - arch: ARCH
  - ip: IP
  - type: Endpoint
  - version: VERSION
  - groups: [GROUPS] (optional)
  - uuid: UUID
  - key: alphanumeric (32 characters)

Example:

```json
{ 
    "os": "Amazon Linux 2", 
    "platform": "amzn",
    "arch": "x86_64",
    "ip": "192.168.1.23",
    "type": "Endpoint", 
    "version": "5.0.0", 
    "groups": ["pepa", "pepe"], 
    "uuid": "skjrowegj12355",
    "key": "7b8276c3bf96aff5709346d368f04fed",
} 
```

## Stateful/stateless requests

- API: Agent Comms

### Authentication:

- Endpoint: `/api/v1/authentication`

- Method: POST

- Headers: _empty_

- Body: _json_
  - uuid: UUID
  - key: alphanumeric (32 characters)

Example:

```json
{ 
    "uuid": "UUID", 
    "key": "7b8276c3bf96aff5709346d368f04fed"
} 
```

### Sateful/stateless

- Endpoint: `/api/v1/events/stateful` `/api/v1/events/stateless`

- Method: POST

- Headers:
  - Authorization: Bearer `token`
  - User_agent: 
    - Agent version. VERSION
    - Agent type. Endpoint
    - Agent arch. ARCH
    - Agent platform. PLATFORM 
    
Ejemplo: `WazuhXDR/5.0.0 (Endpoint; x86_64; Linux)`

- Body: _json_
  - os: OS
  - platform: PLATFORM
  - arch: ARCH
  - ip: IP
  - type: Endpoint
  - version: VERSION
  - groups: [GROUPS] (optional)
  - uuid: UUID

Example:

```json
{
  "agent": {
    "os": "Amazon Linux 2", 
    "platform": "amzn",
    "arch": "x86_64",
    "ip": "192.168.1.23",
    "type": "Endpoint", 
    "version": "5.0.0", 
    "groups": ["pepa", "pepe"], 
    "uuid": "skjrowegj12355" 
  }
}
```

**Comment by Nicogp** [comment]
## Work update

### 2024/11/05

- I added the changes to the AgentInfo class to obtain and return the necessary information for the queries.

**Comment by TomasTurina** [comment]
PR ready for review. Pending some tests.
