### ISSUE TITLE
Design and development of the configuration parser component for the new agent

### ISSUE THREAD

**Issue by TomasTurina** [wazuh/wazuh-agent#26]
**Parent issue:**
- https://github.com/wazuh/wazuh-agent/issues/14

## Description

As part of the development of the new agent [MVP](https://github.com/wazuh/wazuh-agent/issues/14), it is necessary to develop a new configuration parser module.

Take into account the following:

- Configuration will be in TOML format.
  - The name of the configuration file will be `wazuh.conf`.
- Avoid to create a new library for this.
  - Select and use a common and maintained library, mention the advantages and disadvantages of its use.
- This module should be able to parse and save the configuration in memory.
  - Consider STL containers to do this.
- This module should be able to distribute all configuration to all modules.
  - Each module will be in charge of reading and applying its particular configuration.

**Comment by Nicogp** [comment]
## Libraries investigation

The official [TOML Wiki](https://github.com/toml-lang/toml/wiki) lists three C++ libraries:

- [toml11](https://github.com/ToruNiina/toml11)
- [tomlcpp](https://github.com/cktan/tomlcpp)
- [toml++](https://github.com/cktan/tomlcpp)

### toml11
[Documentation](https://toruniina.github.io/toml11/)
Recent activity in the repository.
Licence: MIT
Standar: C++11/14/17/20
Features:

- It complies with [the latest TOML language specification](https://toml.io/en/v1.0.0).
- It supports new features merged into the upcoming TOML version (v1.1.0).
- It provides clear error messages, including the location of the error.
- It parses and retains comments, associating them with corresponding values.
- It provides exception-less parse function.
- It supports complex type conversions from TOML values.
- It allows customization of the types stored in toml::value.


### tomlcpp
[Documentation](https://github.com/cktan/tomlcpp) (Only a Readme)
Last update: two years ago.
Licence: MIT
Standar: This is a C++ wrapper around the C library available here: https://github.com/cktan/tomlc99.
Features:

- Compatible with [TOML v1.0.0](https://toml.io/en/v1.0.0).

- Does not throw C++ exceptions.
- Provides very simple and intuitive interface.

### toml++
[Documentation](https://marzer.github.io/tomlplusplus/)
Last update: 4 months ago.
Licence: MIT
Standar: C++17 (plus some C++20 features where available, e.g. experimental support for [char8_t]
Features:

- Header-only (optional!)
- Supports the latest [TOML](https://toml.io/) release ([v1.0.0](https://toml.io/en/v1.0.0)), plus optional support for some unreleased TOML features
- Supports serializing to JSON and YAML
- Proper UTF-8 handling (incl. BOM)
- C++17 (plus some C++20 features where available, e.g. experimental support for [char8_t](https://en.cppreference.com/w/cpp/language/types#Character_types) strings)
- Doesn't require RTTI
- Works with or without exceptions
- Tested on x64, x86 and ARM

**Comment by Nicogp** [comment]
## Update

- I created the directory structure and code base of the classes.
- Performed tests with toml11 and toml++ library.

**Comment by Nicogp** [comment]
## Update 10/07/2024

An approach is continued in which modules would query the configurationParser for the configuration of a particular block or setting based on keys and following a certain structure.

I have made a test with the configuration block of the github module:

<details><summary>wazuh.conf</summary>

```
[github]
enabled = true
interval = "1m"
time_delay = "1m"
curl_max_size = "1M"
only_future_events = false
api_parameters.api_type = "git"
api_auth = [{org_name = "dummy1", api_token = "api_token1"}, {org_name = "dummy2", api_token = "api_token2"}, {org_name = "dummy3", api_token = "api_token3"}]
```


</details>

<details><summary>configurationParser.hpp with structure definition</summary>

```
#ifndef _CONFIGURATION_PARSER_HPP
#define _CONFIGURATION_PARSER_HPP

#include <iostream>
#include <toml11.hpp>

namespace extlib
{
struct github_config_api_auth
{
    std::string org_name;
    std::string api_token;
};

struct github_config_api_parameters
{
    std::string api_type;
};

struct github_config
{
    bool enabled;
    std::string interval;
    std::string time_delay;
    std::string curl_max_size;
    bool only_future_events;
    github_config_api_parameters api_parameters;
    std::vector<github_config_api_auth> api_auth;
};
} // extlib
TOML11_DEFINE_CONVERSION_NON_INTRUSIVE(extlib::github_config_api_auth, org_name, api_token)
TOML11_DEFINE_CONVERSION_NON_INTRUSIVE(extlib::github_config_api_parameters, api_type)
TOML11_DEFINE_CONVERSION_NON_INTRUSIVE(extlib::github_config, enabled, interval, time_delay, curl_max_size, only_future_events, api_parameters, api_auth)


class configurationParser {
  private:
    std::string config_fileName = "/home/nico/wazuh.config";
    toml::value tbl;
  public:
    configurationParser(){
      tbl = toml::parse(config_fileName, toml::spec::v(1,0,0));
    };
    template<typename T, typename ... Ks>
    auto getConfig(Ks ... ks){
      auto config = toml::find<T>(tbl, ks...);
      return config;
    }
    ~configurationParser(){};
};

#endif // _CONFIGURATION_PARSER_HPP
```

</details>

<details><summary>main.cpp (test)</summary>

```
#include <map>
#include "configurationParser.hpp"

int main()
{
    configurationParser *parser = new configurationParser;

   std::cout << "###### github ######" << "\n\n";
    const extlib::github_config github_config = parser->getConfig<extlib::github_config>("github");
    std::cout << "enabled: " << github_config.enabled << "\n";
    assert(github_config.enabled == true);
    std::cout << "interval: " << github_config.interval << "\n";
    assert(github_config.interval == "1m");
    std::cout << "time_delay: " << github_config.time_delay << "\n";
    assert(github_config.time_delay == "1m");
    std::cout << "curl_max_size: " << github_config.curl_max_size << "\n";
    assert(github_config.curl_max_size == "1M");
    std::cout << "only_future_events: " << github_config.only_future_events << "\n";
    assert(github_config.only_future_events == false);
    std::cout << "api_parameters: " << github_config.api_parameters.api_type << "\n";
    assert(github_config.api_parameters.api_type == "git");
    std::cout << "org_name_1: " << github_config.api_auth[0].org_name << "\n";
    assert(github_config.api_auth[0].org_name == "dummy1");
    std::cout << "api_token_1: " << github_config.api_auth[0].api_token << "\n";
    assert(github_config.api_auth[0].api_token == "api_token1");
    std::cout << "org_name_2: " << github_config.api_auth[1].org_name << "\n";
    assert(github_config.api_auth[1].org_name == "dummy2");
    std::cout << "api_token_2: " << github_config.api_auth[1].api_token << "\n";
    assert(github_config.api_auth[1].api_token == "api_token2");
    std::cout << "org_name_3: " << github_config.api_auth[2].org_name << "\n";
    assert(github_config.api_auth[2].org_name == "dummy3");
    std::cout << "api_token_3: " << github_config.api_auth[2].api_token << "\n";
    assert(github_config.api_auth[2].api_token == "api_token3");


    return 0;
}
```

</details>
