### ISSUE TITLE
Critical Error at Agent Startup Due to Missing `retry_interval_secs` Key in Default Configuration

### ISSUE THREAD

**Issue by vikman90** [wazuh/wazuh-agent#285]
**Parent Issue:** #241

## Description

When starting the Wazuh Agent with the default configuration file (`etc/config/wazuh-agent.yml`), the following critical error is encountered:

```
[2024-11-11 10:14:06.941] [wazuh-agent] [critical] [CRITICAL] [main.cpp:67] [main] An error occurred: Key not found: retry_interval_secs.
```

The agent should be able to operate with its default configuration out of the box. Furthermore, if certain options are not specified in the configuration file, the agent should be able to apply default values instead of failing with an error.

## Expected Behavior

- The agent should start successfully using the default configuration without requiring additional keys.
- Missing keys in the configuration file, such as `retry_interval_secs`, should be handled by applying predefined default values.

## Steps to Reproduce

Start the Wazuh Agent with the default `etc/config/wazuh-agent.yml` configuration:
```shell
./wazuh-agent --config-file ../etc/config/wazuh-agent.yml --run
```

## Proposed Solution

1. Implement a mechanism for handling missing configuration keys by applying default values.
2. Ensure that the `retry_interval_secs` key (and any other essential keys) have sensible defaults within the agent's codebase to prevent startup errors.

**Comment by aritosteles** [comment]
# Update

- **2024/11/11:**
Getting to know yaml-cpp library. Evaluating different approaches.
