### ISSUE TITLE
Update System Inventory Format

### ISSUE THREAD

**Issue by vikman90** [wazuh/wazuh-agent#293]
**Parent Issue:** #292

## Description

Update the system inventory format to comply with the Elastic Common Schema (ECS).

## Data fields

| Field         | Type     | Example |
|--------------|----------|---------|
| agent.groups | keyword |         |
| agent.id | keyword |         |
| host.architecture | keyword |         |
| host.hostname | keyword |         |
| host.name | keyword |         |
| host.os.full | keyword |         |
| host.os.kernel | keyword |         |
| host.os.platform | keyword |         |
| host.os.type | keyword |         |
| host.os.version | keyword |         |

## Tasks

- Map and update all fields in the system inventory according to ECS guidelines.

## References

- Common schema definitions: [Wazuh Indexer Plugins](https://github.com/wazuh/wazuh-indexer-plugins/tree/master/plugins/setup/src/main/resources)
- ECS documentation: [Elastic ECS Documentation](https://www.elastic.co/guide/en/ecs/current/index.html)

**Comment by cborla** [comment]
## Work update

### 2024/11/13

- I have added functions to adapt the information to the ECS format.
- I have created the PR.
