### ISSUE TITLE
Update Network Inventory Format

### ISSUE THREAD

**Issue by vikman90** [wazuh/wazuh-agent#294]
**Parent Issue:** #292

## Description

Update the network inventory format to comply with the Elastic Common Schema (ECS).

## Data Fields

| Field         | Type     | Example |
|--------------|----------|---------|
| agent.groups | keyword |         |
| agent.id | keyword |         |
| host.ip | ip |         |
| host.mac | keyword |         |
| host.network.egress.bytes | long |         |
| host.network.egress.drops | long |         |
| host.network.egress.errors | long |         |
| host.network.egress.packets | long |         |
| host.network.ingress.bytes | long |         |
| host.network.ingress.drops | long |         |
| host.network.ingress.errors | long |         |
| host.network.ingress.packets | long |         |
| network.broadcast | ip |         |
| network.dhcp | keyword |         |
| network.gateway | ip |         |
| network.metric | long |         |
| network.netmask | ip |         |
| network.protocol | keyword |         |
| network.type | keyword |         |
| observer.ingress.interface.alias | keyword |         |
| observer.ingress.interface.name | keyword |         |

## Tasks

- Update the unified network inventory structure (interface, protocol, and address) according to ECS.

## Dependencies

- https://github.com/wazuh/wazuh-agent/issues/284

## References

- Common schema definitions: [Wazuh Indexer Plugins](https://github.com/wazuh/wazuh-indexer-plugins/tree/master/plugins/setup/src/main/resources)
- ECS documentation: [Elastic ECS Documentation](https://www.elastic.co/guide/en/ecs/current/index.html)

**Comment by cborla** [comment]
## Work report

### November 21

- PR created.
- Adapt configuration tables names wazuh-agent.yml file.

**Comment by cborla** [comment]
Tables Documentarion https://github.com/wazuh/wazuh-indexer/tree/master/ecs/docs

**Comment by cborla** [comment]
### Adapted table
``` json
{
    "id": "aW52ZW50b3J5Om5ldHdvcmtzOmVucDBzODo6aXB2Njo6ZmU4MDo6ZjgyNzplZTQ5OmNmMmY6ZTVkNA==",
    "module": "inventory",
    "operation": "modified",
    "type": "networks"
}
{
    "@timestamp": "2024/11/26 20:05:00",
    "host":
    {
        "ip":
        [
            "fe80::f827:ee49:cf2f:e5d4"
        ],
        "mac": "08:00:27:70:ef:90",
        "network":
        {
            "egress":
            {
                "bytes": 19895265,
                "drops": 0,
                "errors": 0,
                "packets": 293039
            },
            "ingress":
            {
                "bytes": 31233438,
                "drops": 0,
                "errors": 0,
                "packets": 311627
            }
        }
    },
    "interface":
    {
        "mtu": 1500,
        "state": "up",
        "type": "ethernet"
    },
    "network":
    {
        "broadcast": "",
        "dhcp": "unknown",
        "gateway": " ",
        "metric": "",
        "netmask": "ffff:ffff:ffff:ffff::",
        "protocol": "",
        "type": "ipv6"
    },
    "observer":
    {
        "ingress":
        {
            "interface":
            {
                "alias": "",
                "name": "enp0s8"
            }
        }
    }
}
```
