### ISSUE TITLE
Update Processes Inventory Format

### ISSUE THREAD

**Issue by vikman90** [wazuh/wazuh-agent#295]
**Parent Issue:** #292

## Description

Update the processes inventory format to comply with the Elastic Common Schema (ECS).

## Data Fields

| Field         | Type     | Example |
|--------------|----------|---------|
| agent.groups | keyword |         |
| agent.id | keyword |         |
| process.args | keyword |         |
| process.command_line | wildcard |         |
| process.group.id | keyword |         |
| process.name | keyword |         |
| process.parent.pid | long |         |
| process.pid | long |         |
| process.real_group.id | keyword |         |
| process.real_user.id | keyword |         |
| process.saved_group.id | keyword |         |
| process.saved_user.id | keyword |         |
| process.start | date |         |
| process.thread.id | long |         |
| process.user.id | keyword |         |

## Tasks

- Map and update all fields in the processes inventory according to ECS guidelines.

## References

- Common schema definitions: [Wazuh Indexer Plugins](https://github.com/wazuh/wazuh-indexer-plugins/tree/master/plugins/setup/src/main/resources)
- ECS documentation: [Elastic ECS Documentation](https://www.elastic.co/guide/en/ecs/current/index.html)

**Comment by cborla** [comment]
## Work update

### 2024/11/14

- I have started the fix on a local branch.
- Testing that it works as expected.
