### ISSUE TITLE
Update Hardware Inventory Format

### ISSUE THREAD

**Issue by vikman90** [wazuh/wazuh-agent#296]
**Parent Issue:** #292

## Description

Update the hardware inventory format to comply with the Elastic Common Schema (ECS).

## Data Fields

| Field         | Type     | Example |
|--------------|----------|---------|
| agent.groups | keyword |         |
| agent.id | keyword |         |
| host.cpu.cores | long |         |
| host.cpu.name | keyword |         |
| host.cpu.speed | long |         |
| host.memory.free | long |         |
| host.memory.total | long |         |
| host.memory.used.percentage | long |         |
| observer.serial_number | keyword |         |

## Tasks

- Map and update all fields in the hardware inventory according to ECS guidelines.

## References

- Common schema definitions: [Wazuh Indexer Plugins](https://github.com/wazuh/wazuh-indexer-plugins/tree/master/plugins/setup/src/main/resources)
- ECS documentation: [Elastic ECS Documentation](https://www.elastic.co/guide/en/ecs/current/index.html)

**Comment by Nicogp** [comment]
## Work update

### 2024/11/13

- We have added functions to adapt the information to the ECS format.
- I have created the PR
