### ISSUE TITLE
Update Hotfixes Inventory Format

### ISSUE THREAD

**Issue by vikman90** [wazuh/wazuh-agent#298]
**Parent Issue:** #292

## Description

Update the hotfixes inventory format to comply with the Elastic Common Schema (ECS).

## Data Fields

| Field         | Type     | Example |
|--------------|----------|---------|
| agent.groups | keyword |         |
| agent.id | keyword |         |
| package.hotfix.name | keyword |         |

## Tasks

- Map and update all fields in the hotfixes inventory according to ECS guidelines.

## References

- Common schema definitions: [Wazuh Indexer Plugins](https://github.com/wazuh/wazuh-indexer-plugins/tree/master/plugins/setup/src/main/resources)
- ECS documentation: [Elastic ECS Documentation](https://www.elastic.co/guide/en/ecs/current/index.html)

**Comment by cborla** [comment]
```json
{
    "id": "aW52ZW50b3J5OmhvdGZpeGVzOktCMTIzNDU2Nzg=",
    "module": "inventory",
    "operation": "create",
    "type": "hotfixes"
}
{
    "package":
    {
        "hotfix":
        {
            "name": "KB12345678"
        }
    }
}
```
