### ISSUE TITLE
Research the necessary migration from wazuh-packages to Agent repository

### ISSUE THREAD

**Issue by vikman90** [wazuh/wazuh-agent#30]
| Objective |
|-----|
| https://github.com/wazuh/wazuh-packages/issues/2904 |

## Description

The code related to the Wazuh agent package generation must be migrated from the repository `wazuh-packages` to its new repository, this issue aims to analyze and document what must be migrated.

## Tasks

- Research the `wazuh-packages` repository for agent package-related code
- Define and document the content desired to migrate

**Comment by mjcr99** [comment]
## Update
**(09/07/2024)** Reviewing migrated and its requirements.

**Comment by MarcelKemp** [comment]
## Review

| Folder | Decision | Comment |
|------|------|------|
| [/wazuh-packages/.github/workflows](https://github.com/wazuh/wazuh-packages/tree/master/.github) | Pending | It would be necessary to remove the workflows that are already migrated in wazuh/wazuh, and make a list of those that have not been merged (such as package testing), to verify that we cover those cases. |
| [/wazuh-packages/aix](https://github.com/wazuh/wazuh-packages/tree/master/aix) | Don't migrate | It is explicitly stated in the issue that we do not migrate it: https://github.com/wazuh/wazuh-packages/issues/2904#issue-2230731580 |
| [/wazuh-packages/alpine](https://github.com/wazuh/wazuh-packages/tree/master/alpine) | Don't migrate | It is explicitly stated in the issue that we do not migrate it: https://github.com/wazuh/wazuh-packages/issues/2904#issue-2230731580 |
| [/wazuh-packages/arch](https://github.com/wazuh/wazuh-packages/tree/master/arch) | Don't migrate | Although not listed, this OS is also not listed in the compatibility table. |
| [/wazuh-packages/debs](https://github.com/wazuh/wazuh-packages/tree/master/debs) | Don't migrate + Clean up | Migrated in wazuh/wazuh. For `5.0` it will be migrated to this repository, however for this objective it is not necessary. |
| [/wazuh-packages/documentation-templates](https://github.com/wazuh/wazuh-packages/tree/master/documentation-templates) | Don't migrate + Clean up ([filebeat](https://github.com/wazuh/wazuh-packages/tree/master/documentation-templates/wazuh/filebeat)) | Remove the contents of **Filebeat** or notify the relevant team to remove this directory. |
| [/wazuh-packages/hp-ux](https://github.com/wazuh/wazuh-packages/tree/master/hp-ux) | Don't migrate | It is explicitly stated in the issue that we do not migrate it: https://github.com/wazuh/wazuh-packages/issues/2904#issue-2230731580 |
| [/wazuh-packages/macos](https://github.com/wazuh/wazuh-packages/tree/master/macos) | Don't migrate + Clean up | Migrated in wazuh/wazuh. For `5.0` it will be migrated to this repository, however for this objective it is not necessary. |
| [/wazuh-packages/ova](https://github.com/wazuh/wazuh-packages/tree/master/ova) | Don't migrate | :+1: |
| [/wazuh-packages/puppet_module](https://github.com/wazuh/wazuh-packages/tree/master/puppet_module) | Don't migrate | :+1: |
| [/wazuh-packages/rpms](https://github.com/wazuh/wazuh-packages/tree/master/rpms) | Don't migrate + Clean up | Migrated in wazuh/wazuh. For `5.0` it will be migrated to this repository, however for this objective it is not necessary. |
| [/wazuh-packages/solaris](https://github.com/wazuh/wazuh-packages/tree/master/solaris) | Don't migrate | It is explicitly stated in the issue that we do not migrate it: https://github.com/wazuh/wazuh-packages/issues/2904#issue-2230731580 |
| [/wazuh-packages/splunkapp](https://github.com/wazuh/wazuh-packages/tree/master/splunkapp) | Don't migrate | :+1: |
| [/wazuh-packages/stack](https://github.com/wazuh/wazuh-packages/tree/master/stack) | Don't migrate | :+1: |
| [/wazuh-packages/test/unattended_installer](https://github.com/wazuh/wazuh-packages/tree/master/test/unattended_installer) | Don't migrate + Clean up (filebeat) | Remove the contents of **Filebeat** or notify the relevant team to remove this directory. |
| [/wazuh-packages/wazuhapp](https://github.com/wazuh/wazuh-packages/tree/master/wazuhapp) | Don't migrate | :+1: |
| [/wazuh-packages/windows](https://github.com/wazuh/wazuh-packages/tree/master/windows) | Don't migrate + Clean up | Migrated in wazuh/wazuh. For `5.0` it will be migrated to this repository, however for this objective it is not necessary. |
| [/wazuh-packages/wpk](https://github.com/wazuh/wazuh-packages/tree/master/wpk)  | Don't migrate + Clean up | Migrated in wazuh/wazuh. For `5.0` it will be migrated to this repository, however for this objective it is not necessary. |

**Comment by MarcelKemp** [comment]
## Review

### Workflows: 
These are workflows to simply test the installation of the generated packages on an array of OSes from different distributions and architectures that support the package:
- [Test install .deb](https://github.com/wazuh/wazuh-packages/blob/master/.github/workflows/test-install-deb.yml)
- [Test install .rpm](https://github.com/wazuh/wazuh-packages/blob/master/.github/workflows/test-install-rpm.yml)
  - Both run the same script: [install_component.sh](https://github.com/wazuh/wazuh-packages/blob/master/.github/actions/test-install-components/install_component.sh). Where the check is simply: `$sys_type install -y "/packages/$1"`.

This check to install the package is already done in the same workflow, although it is tested only on the same machine used to generate the package:
- https://github.com/wazuh/wazuh-agent-packages/blob/8168cb4ac57c366ba8fc76f4ed93d7339eaee0de/.github/workflows/packages-build-linux-agent-amd.yml#L159-L172


| Folder | Decision | Comment |
|------|------|------|
| [/wazuh-packages/.github/workflows](https://github.com/wazuh/wazuh-packages/tree/master/.github) | Don't migrate + Clean up | I consider that with the current smoke tests, we already perform the same check, although limited based on the test matrix. However, I believe that this matrix will be tested with additional tests (such as DTT), so there is no need to migrate it. |

**Comment by MarcelKemp** [comment]
## Conclusion

| Folder | Decision |
|------|------|
| [/wazuh-packages/.github/workflows](https://github.com/wazuh/wazuh-packages/tree/master/.github) | Don't migrate + Clean up | 
| [/wazuh-packages/aix](https://github.com/wazuh/wazuh-packages/tree/master/aix) | Don't migrate | 
| [/wazuh-packages/alpine](https://github.com/wazuh/wazuh-packages/tree/master/alpine) | Don't migrate | 
| [/wazuh-packages/arch](https://github.com/wazuh/wazuh-packages/tree/master/arch) | Don't migrate | 
| [/wazuh-packages/debs](https://github.com/wazuh/wazuh-packages/tree/master/debs) | Clean up | 
| [/wazuh-packages/documentation-templates](https://github.com/wazuh/wazuh-packages/tree/master/documentation-templates) | Clean up ([filebeat](https://github.com/wazuh/wazuh-packages/tree/master/documentation-templates/wazuh/filebeat)) | 
| [/wazuh-packages/hp-ux](https://github.com/wazuh/wazuh-packages/tree/master/hp-ux) | Don't migrate | 
| [/wazuh-packages/macos](https://github.com/wazuh/wazuh-packages/tree/master/macos) | Clean up | 
| [/wazuh-packages/ova](https://github.com/wazuh/wazuh-packages/tree/master/ova) | Do nothing | 
| [/wazuh-packages/puppet_module](https://github.com/wazuh/wazuh-packages/tree/master/puppet_module) | Do nothing |
| [/wazuh-packages/rpms](https://github.com/wazuh/wazuh-packages/tree/master/rpms) | Clean up | 
| [/wazuh-packages/solaris](https://github.com/wazuh/wazuh-packages/tree/master/solaris) | Don't migrate |
| [/wazuh-packages/splunkapp](https://github.com/wazuh/wazuh-packages/tree/master/splunkapp) | Do nothing |
| [/wazuh-packages/stack](https://github.com/wazuh/wazuh-packages/tree/master/stack) | Do nothing | 
| [/wazuh-packages/test/unattended_installer](https://github.com/wazuh/wazuh-packages/tree/master/test/unattended_installer) | Clean up (filebeat) | 
| [/wazuh-packages/wazuhapp](https://github.com/wazuh/wazuh-packages/tree/master/wazuhapp) | Do nothing |
| [/wazuh-packages/windows](https://github.com/wazuh/wazuh-packages/tree/master/windows) | Clean up | 
| [/wazuh-packages/wpk](https://github.com/wazuh/wazuh-packages/tree/master/wpk)  | Clean up |
