### ISSUE TITLE
Split Wazuh agent and manager

### ISSUE THREAD

**Issue by vikman90** [wazuh/wazuh-agent#31]
**Parent issue:**
- https://github.com/wazuh/wazuh/issues/22888

## Description

This task consists of completing the separation of the agent and manager. However, since the two repositories have already been separated and the interaction between the agent and server has been redesigned, most of the work has been done.

## Functional requirements

1. Vulnerability Scanner does not need to exclude agent 000.

## Non-functional requirements

1. The agent code must not include conditional directives (e.g., `#ifdef CLIENT`).
2. Rootcheck should be assumed to function as a daemon (e.g., `#ifdef OSSECHIDS`).

## Implementation restrictions

1. The agent and the manager should not share code.

## Plan

1. https://github.com/wazuh/wazuh-agent/issues/70
2. https://github.com/wazuh/wazuh-agent/issues/71
3. https://github.com/wazuh/wazuh-agent/issues/72
4. https://github.com/wazuh/wazuh/issues/24917

**Comment by sdvendramini** [comment]
### Update 06/08/24
I started with the task, reviewing what needs to be done and how the code currently looks.
