### ISSUE TITLE
Introduce Data Directory Configuration

### ISSUE THREAD

**Issue by vikman90** [wazuh/wazuh-agent#315]
**Parent Issue:** #241

## Description
Currently, the agent creates its local databases in the current working directory.

## Proposal
1. Add a new configuration option, `path.data`, in the `wazuh-agent.yml` file.
2. Default value for `path.data`: `/var/lib/wazuh-agent`.
3. Store all local databases and modifiable files in the specified data directory.

**Comment by vikman90** [comment]
## Work report

### November 20

- Added new option `data.path`.
- Option parsed and applied for `agent_info.db`.

**Comment by cborla** [comment]
## Work report

### November 20

- PR created.
- Included config.h to agent_info Cmakelist.
- Fixed clang format.
