### ISSUE TITLE
Test the agent execution with a real server and indexer

### ISSUE THREAD

**Issue by TomasTurina** [wazuh/wazuh-agent#326]
## Description

This issue aims to tests the agent with a real server and indexer to validate that everything works as expected.

The following OSs need to be tested:
- Linux DEB.
- Linux RPM.
- MacOS.
- Windows.

Considerations:
- Use one machine to install the server and indexer.
  - Indexer should be installed first.
- Use a different machine to install the agent.
  - One for each OS required to test.
- Use packages to install every component.
  - Generate new ones with the latest code or ask to the corresponding team for them.
- Tests can be done using different virtual machines, AWS machines, physical machines, or a combination of them.

Tests:
- The agent can authenticate and register successfully (API `55000`).
  - It is added to the indexer (`/agents`).
- The agent can authenticate with the server (API `27000`).
  - A valid token is received.
- The agent can receive commands (API `27000`).
  - They are stored in the command store and processed by the command manager.
- The agent can send stateful messages with a successful response (API `27000`).
  - Use inventory for this test.
  - Events are added to the indexer.
- The agent can send stateless messages with a successful response (API `27000`).
  - Use logcollector for this test.
  - Events are processed by the engine in the server side.

> Note: Document all the steps followed in this issue from components installation to testing results.

**Comment by aritosteles** [comment]
# Update

- **2024/11/20:**
Setting up environment.

**Comment by aritosteles** [comment]
# Ubuntu Agent Installation

- Installed the agent 5.0 package using `dpkg -i`

![image](https://github.com/user-attachments/assets/9b6dd830-c140-4bc6-b6ec-314fc65ab1d1)

**Comment by aritosteles** [comment]
# CentOS Agent

- Same installation procedure and settings used in Ubuntu

- Agent registered and running

![image](https://github.com/user-attachments/assets/4400f0e5-40ae-4c33-b401-222f5f2d7088)

**Comment by aritosteles** [comment]
# Update
- Updated to Agent package [wazuh-agent_5.0.0-0_amd64_8654369.deb.zip](https://github.com/wazuh/wazuh-agent-packages/actions/runs/12047088397) 
- Installed with `dpkg -i` and answered 'N' when prompted, so my config was not overwritten.
- Removed `/var/lib/wazuh-agent/agent_info.db' and registered the agent:

![image](https://github.com/user-attachments/assets/450322b3-ec58-4b21-876b-6fcf8ab51f7b)

**Comment by TomasTurina** [comment]
A 400 error is expected to appear in response to stateful requests, as the team needs to fix the request body.

The rest of the tests LGTM.
