### ISSUE TITLE
Error when cloudtrail home region is me-south-1

### ISSUE THREAD

**Issue by integratechfze** [wazuh/wazuh-agent#327]
We are using wazuh agent to send our cloudtrail logs wazuh. Our cloudtrail home region is me-south-1 and the cloudtrail log bucket is in the same region. We can see this error in the logs :

<img width="2192" alt="Screenshot 2024-11-21 at 9 27 46 AM" src="https://github.com/user-attachments/assets/3bf25080-f495-4beb-8907-368a804c3a99">

Is there any configuration options i can pass in the ossec conf to include the me-south-1 region in the aws cli request ?

**Comment by jr0me** [comment]
Hello @integratechfze can you share with us your `ossec.conf` to see how you configured the aws-s3 wodle?

(Beware to hide any sensitive data like tokens or credentials)

**Comment by TomasTurina** [comment]
Closed because there has been no new activity for 2 weeks.
