### ISSUE TITLE
Rework Antitampering functionality to use in the new agent 5.0

### ISSUE THREAD

**Issue by jotacarma90** [wazuh/wazuh-agent#333]
# Description

Hi team, after the changes we are making to the agent in 5.0, if we want to continue having the anti-tampering functionality we are going to need to make some additions.
- This is the original issue: https://github.com/wazuh/wazuh/issues/23466
- PR where all the functionality is included: https://github.com/wazuh/wazuh/pull/24526

The main problem is that we were using the agentd daemon to activate this utility in the configuration. And now with the changes made, we have to find another way to do it. The rest of the files and scripts can be reused.

**Comment by vikman90** [comment]
@jotacarma90, we are not going to implement this functionality in the agent at the moment, but thanks for the proposal.

Best.
