### ISSUE TITLE
Unexpected Prompt About PackageKit Restart When Installing Wazuh Agent DEB After `apt purge`

### ISSUE THREAD

**Issue by vikman90** [wazuh/wazuh-agent#347]
**Parent Issue:** #241 

## Description

After completely removing the Wazuh Agent DEB package using `apt purge`, reinstalling the package triggers an unexpected prompt during the installation process. The prompt asks whether the `packagekit` service should be restarted. This behavior is unusual and not expected during the installation of the Wazuh Agent.

![image](https://github.com/user-attachments/assets/fb39ec69-60ca-43b3-8e1e-b7272508c1bf)

## Expected Behavior

- Installing the Wazuh Agent DEB package should proceed without any prompts related to `packagekit` or unrelated services.

## Steps to Reproduce

1. Install the Wazuh Agent DEB package:
   ```bash
   sudo apt install ./wazuh-agent_x.x.x_xxx.deb
   ```
2. Remove the package completely:
   ```bash
   sudo apt purge wazuh-agent
   ```
3. Reinstall the same package:
   ```bash
   sudo apt install ./wazuh-agent_x.x.x_xxx.deb
   ```
4. Observe the unexpected prompt about restarting the `packagekit` service.

## Root Cause Hypothesis

This behavior might be linked to:
1. Incorrect dependencies or hooks included in the DEB package.
2. An unexpected interaction with `systemd` service management during the installation process.

## Tasks

1. Investigate the package metadata and scripts (`preinst`, `postinst`, etc.) to identify any triggers or dependencies related to `packagekit`.
2. Verify if the `packagekit` service is being incorrectly referenced or affected during the package installation.
3. Adjust the package configuration to eliminate the prompt unless absolutely necessary.
4. Test the updated package to ensure the prompt no longer appears.

**Comment by jotacarma90** [comment]
# Update 25/11/2024
- Researching packagekit
- Problem reproduced very easily.
- Researching possible triggers related to packagekit:
  - I have read that it could be the modification or use of the following path:
    - `usr/lib/`
    - `/etc/dbus-1/system.d/`
    - `/etc/`
  - `Could be related to libc-bin`
- Testing different changes in `postinst` script.

**Comment by jotacarma90** [comment]
This issue can be closed with: https://github.com/wazuh/wazuh-agent/pull/375
By converting the libstdc++ library to static, it is no longer necessary to restart any process. The initial PR for this issue has been closed.
