### ISSUE TITLE
Make agent modules have their own threads

### ISSUE THREAD

**Issue by TomasTurina** [wazuh/wazuh-agent#363]
**Parent Issue:** #241

## Description

Currently, modules are designed to run in their own thread. However, they are executed by the task manager together with the coroutines that run the agent's core components. This causes the modules to run as a core component instead of a separate thread to handle its own functions as expected.

To solve this, the proposed solution is to launch each module as a separate thread capable of handling its own tasks and running in a separate location from the main agent components. This solution fits better with the current design of modules and has its benefits, as for example this will allow to easily stop the execution of modules, including their own coroutines.

**Comment by jr0me** [comment]
### Update

Started looking into the issue and its requirements. Will make a first attempt using the TaskManager as data members for the modules.

**Comment by jr0me** [comment]
## Update

Created branch, removed timers from task manager tests, added tests for the thread counter, improved the enqueuing of tasks by enclosing them in try/ctatch blocks. Tested these changes.

**Comment by jr0me** [comment]
## Update

Added a TaskManager to the ModuleManager. Modules threads/coroutines now don't share a context with the Agent, but they still come from an unique pool. If each module needs to have its own context and pool of threads, they'll need a TaskManager as well. Will test this and assess.

**Comment by jr0me** [comment]
## Update

Tested the ModuleManager having its own TaskManager and sharing it with the modules. So far no problems where found.

**Comment by jr0me** [comment]
## Update

Ran more tests, code is ready for code review.

**Comment by jr0me** [comment]
## Update

Dealing with some crashes in tests, caused by the changes in the TaskManager and ModuleManager.

**Comment by jr0me** [comment]
## Update

I'm still debugging the crashes and deadlocks. These tests take time since occurrences are random. I was able to simplify the tests so they don't fail anymore but I've found a segmentation fault when executing commands (by including https://github.com/wazuh/wazuh-agent/pull/408 ).

I've been trying to find the cause with valgrind, but it seems that the segmentation fault doesn't occur as often when run under this tool.

**Comment by jr0me** [comment]
## Update

I've located the segmentation fault, which came from the command dispatch coroutines, specifically the timeout cancellation mechanism. Fixed and merged.
