### ISSUE TITLE
Improve Error Messaging for URL Validation in Agent Registration

### ISSUE THREAD

**Issue by vikman90** [wazuh/wazuh-agent#366]
**Related Issue:** #241

## Description

When registering the Wazuh Agent using the `--register-agent` flag, the agent fails to properly validate the provided URL when it lacks a port. This leads to an unclear error message during the registration process.

For example, executing the following command:

```bash
./wazuh-agent --config-file wazuh-agent.yml --register-agent --url https://localhost --user wazuh --password topsecret --name dummy
```

Results in the following error message:

```
Starting wazuh-agent registration
[2024-11-29 13:19:56.483] [wazuh-agent] [error] [ERROR] [http_client.cpp:356] [PerformHttpRequestInternal] Error: Error connecting to host: Connection refused.
[2024-11-29 13:19:56.483] [wazuh-agent] [warning] [WARN] [http_client.cpp:281] [AuthenticateWithUserPassword] Error: 500.
Failed to authenticate with the manager
wazuh-agent registration failed
```

The error message does not clearly indicate that the URL is invalid due to the missing port, and the agent does not provide feedback on how to fix the issue.

## Steps to Reproduce

1. Run the Wazuh Agent registration command with a URL missing a port:
   ```bash
   ./wazuh-agent --config-file wazuh-agent.yml --register-agent --url https://localhost --user wazuh --password topsecret --name dummy
   ```
2. Observe the error message provided by the agent.

## Expected Behavior

The agent should validate the URL parameters at the beginning of the registration process and provide a clear error message if the URL is incomplete or missing a required component.

### Default values

- **Schema**: https
- **Port**:
   - 80 for http
   - 443 for https

## Proposed Solution

- Add a validation step in the registration process to check the provided URL format before attempting any network communication.
- Update the error message to explicitly indicate that the URL must include protocol, host, and port.

**Comment by TomasTurina** [comment]
## Update

The Boost library has some limitations. Example:

```
# ./wazuh-agent --register-agent --user wazuh --password wazuh --url localhost --config-file wazuh-agent.yml 
Starting wazuh-agent registration
[2024-12-03 20:05:56.474] [wazuh-agent] [error] [ERROR] [http_request_params.cpp:26] [HttpRequestParams] Invalid URL: need more
[2024-12-03 20:05:56.475] [wazuh-agent] [error] [ERROR] [http_client.cpp:402] [PerformHttpRequestInternal] Error: Failed to resolve host..
[2024-12-03 20:05:56.475] [wazuh-agent] [warning] [WARN] [http_client.cpp:326] [AuthenticateWithUserPassword] Error: 500.
Failed to authenticate with the manager
wazuh-agent registration failed
```

As you can see above, the URL scheme cannot be inferred if it is not specified.

We need to find an alternative or use the library in a different way to solve this.

**Comment by TomasTurina** [comment]
## Update

Since the requirement to optionally specify the URL scheme has been removed, the boost library can still be used to parse the URL. Depending on the scheme, if the port is empty, it will be mapped to 80 or 443. If the scheme is not recognized, an error will be logged. In either case, if the connection fails, the URL used to connect to the server will be added to the log to provide more information to the user.
