### ISSUE TITLE
Adjust Debian Package Behavior to Preserve Data on `remove` Command

### ISSUE THREAD

**Issue by vikman90** [wazuh/wazuh-agent#374]
**Parent Issue:** #241

## Description

The current behavior of the Debian package for the Wazuh Agent is inconsistent with the standard packaging guidelines for the `remove` command. Specifically, when uninstalling the package using `remove`, configuration files are preserved in `/etc/wazuh-agent`, but the data directory `/var/lib/wazuh-agent` is deleted.

This proposal suggests modifying the package behavior to ensure that both configuration and data files are preserved when using the `remove` command. The `purge` command will continue to delete all associated files, including both configuration and data.

## Expected Behavior

- **`remove` command**:
  - Preserve configuration files: `/etc/wazuh-agent`.
  - Preserve data files: `/var/lib/wazuh-agent`.
- **`purge` command**:
  - Remove all files, including configuration and data directories.

## Current Behavior

- **`remove` command**:
  - Preserves `/etc/wazuh-agent`.
  - Deletes `/var/lib/wazuh-agent`.
- **`purge` command**:
  - Removes all files.

## Proposed Solution

Update the Debian packaging scripts to ensure that `/var/lib/wazuh-agent` is not deleted during the execution of the `remove` command.

This change aligns with the Debian packaging standard, where the `remove` command is expected to retain user data and configuration to facilitate reinstallation or troubleshooting without loss of critical information.

**Comment by lchico** [comment]
# Update
Improved the code and created the PR. It is ready for review.
- https://github.com/wazuh/wazuh-agent/pull/379
