### ISSUE TITLE
Update to ECS the Inventory module.

### ISSUE THREAD

**Issue by cborla** [wazuh/wazuh-agent#397]
## Description  

Align the Inventory tables with the latest ECS (Elastic Common Schema)

## Tasks  

- System
  - Analyze why kernel is empty.
- Networks
  - Device id is in the documentation but it is not in the indexer nor in the agent, (remove from documentation).
  - Metric says it is a long.
  - Validate ip.
  - Fix ipv6 broadcast.
- Ports
  - Validate ip.
- Processes
  - Start date must have timestamp format.
- Packagess
  - Installed date is empty.

## DoD  

- Ensures compatibility with the latest ECS standards.  
- Provides detailed and structured information about terminal devices, improving data granularity and usability.

**Comment by Dwordcito** [comment]
This issues includes the fix of ISO8601 datetime fix.
