### ISSUE TITLE
Unable to open `rpmrc` file during Inventory Scan

### ISSUE THREAD

**Issue by cborla** [wazuh/wazuh-agent#404]
**Parent Issue**: #241

## Description

When running the Wazuh Agent on RHEL, an error occurs during the inventory scan related to the `rpmrc` file. The agent logs indicate the following message:

``` 
Dec 06 14:56:25 rhel-agent env[8242]: [2024-12-06 14:56:25.548] [wazuh-agent] [info] [INFO] [inventoryImp.cpp:900] [Scan] Starting evaluation.
Dec 06 14:56:25 rhel-agent env[8242]: error: Unable to open /build_wazuh/rpmbuild/BUILD/wazuh-agent-5.0.0/src/build/vcpkg_installed/x64-linux/debug/lib/rpm/rpmrc for reading: No such file or directory.
Dec 06 14:56:25 rhel-agent env[8242]: [2024-12-06 14:56:25.968] [wazuh-agent] [info] [INFO] [inventoryImp.cpp:912] [Scan] Evaluation finished.
```

Despite this error, the scan evaluation completes successfully, as indicated in the logs:

## Steps to Reproduce

1. Deploy Wazuh Agent on RHEL.
2. Configure the agent with inventory scanning enabled.
3. Start the agent and observe the logs during the inventory scan.

## Expected Behavior

The inventory scan should complete without attempting to access an invalid path for the `rpmrc` file.

## Actual Behavior

The agent attempts to access a non-existent `rpmrc` file, producing an error in the logs.

## Environment

- **Wazuh Agent version:** 5.0.0
- **OS:** RHEL
- **Error message:**

`error: Unable to open /build_wazuh/rpmbuild/BUILD/wazuh-agent-5.0.0/src/build/vcpkg_installed/x64-linux/debug/lib/rpm/rpmrc for reading: No such file or directory.`

## Possible Causes

- The path to the `rpmrc` file may be hardcoded or incorrectly configured during the build process.
- The required `rpmrc` file is missing from the package.

## Suggested Fix

- Verify the build process to ensure the correct path for the `rpmrc` file is configured.
- Update the inventory module to gracefully handle missing configuration files.

**Comment by nbertoldo** [comment]
### Update 2024/12/09

- Setting up the environment: Wazuh Agent on RHEL

**Comment by nbertoldo** [comment]
### Update 2024/12/11

The problem occurs because _vcpkg_, when installing _librpm_ automatically adds a `--prefix` option to the `configure` command to install the files inside the directory structure managed by _vcpkg_, in this case (--prefix=/home/vagrant/wazuh-agent/build/vcpkg_installed/x64-linux/debug). This behavior is intentional, as it ensures that the installed libraries do not interfere with the base system and are kept in the _vcpkg_ workspace.

```console
 $ ./../src/9ed556c157-1b82a7a6d4.clean/configure --prefix=/usr --with-crypto=openssl --enable-sqlite=yes --disable-openmp --disable-plugins --enable-ndb --enable-bdb-ro --disable-silent-rules --verbose --disable-shared --enable-static --prefix=/home/vagrant/wazuh-agent/build/vcpkg_installed/x64-linux/debug '--bindir=${prefix}/../tools/librpm/debug/bin' '--sbindir=${prefix}/../tools/librpm/debug/sbin' '--libdir=${prefix}/lib' '--includedir=${prefix}/../include' '--datarootdir=${prefix}/share/librpm'
```

Then in the _rpm_ _configure.ac_ file this parameter is used to get the `RPMCONFIGDIR`:

```bash
if test X“$prefix” = XNONE ; then
    usrprefix=“$ac_default_prefix” ; then
else
    usrprefix=$prefix
fi

RPMCONFIGDIR="`echo ${usrprefix}/lib/rpm`”
AC_SUBST(RPMCONFIGDIR) 
```

**Proposed solution:** add this line to _portfile.cmake_ to replace the value of the `RPMCONFIGDIR` variable before running `configure`:

```cmake
vcpkg_replace_string("${SOURCE_PATH}/configure.ac" "RPMCONFIGDIR=\"`echo \${usrprefix}/lib/rpm`\"" "RPMCONFIGDIR=\"/usr/lib/rpm\"")
```
