### ISSUE TITLE
Recurrent creation of faulty databases

### ISSUE THREAD

**Issue by NahuFigueroa97** [wazuh/wazuh-agent#462]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.8.2 | Wazuh component | Manager | Packages/Sources | centOS 7 |

## Description

Related to https://github.com/wazuh/internal-devel-requests/issues/1825 it has been discovered that despite deleting the faulty databases and restarting the manager, new faulty databases are still being created. The .profile.db and other databases were checked and no errors were found. It was not possible to reproduce the workaround proposed in https://github.com/wazuh/wazuh/issues/22847#issuecomment-2114968242

**Comment by TomasTurina** [comment]
Solved.
