### ISSUE TITLE
Address technical debt for the new agent MVP

### ISSUE THREAD

**Issue by TomasTurina** [wazuh/wazuh-agent#64]
## Description

As part of the development of the new agent [MVP](https://github.com/wazuh/wazuh-agent/issues/14), a new task manager, configuration parser and communicator module were developed.

The following technical debts will be addressed for this issue:

- [x] Revise `CMakeLists.txt` files.
  - [x] Delete unnecessary steps and comments.
  - [x] Create a separate file for tests in all components.
- [x] Move stateful and stateless co-routines to the communicator module.
  - [x] Remove `message_task` files.
  - [x] Remove `GetToken` function.
- [x] Create a single function to send HTTP requests.
  - [x] Remove duplicated functions.
  - [x] Move all API paths and parameter names to a common place.
- [x] Make communicator functions more testable.
  - [x] Make them independent from the server script.
- [x] Improve the way the token is requested.
  - [x] Error handling.
- [x] Revise function names and parameters.
  - [x] Use a standardized naming for functions.
  - [x] Use `const` where necessary.
  - [x] Remove unnecessary comments.
  - [x] Remove duplicated code/functions when possible.
- [x] Create a main routine for the agent.
  - [x] Handle exit signal to stop execution.
- [ ] Include a logger. **(will do in a new issue)**
  - [ ] Remove `cout` and `cerr` usages.
- [x] Add queue to command retriever co-routine to queue commands.
- [x] Differentiate between Server Management API port and Agent Comms API port.

**Comment by jr0me** [comment]
### Update

Current progresss:

* A branch was created to work on this issue, and linked to it.
* CMake files have been cleaned up and fixed, message tasks (coroutines) have been moved to be a part of the Communicator class.
* All tests now have a corresponding tests subfolder with a CMake file.
* Removed some duplicated code related to http requests using boost.
* Some style and convention fixes were also made.
* Signal handling has been added to the Agent, we can now terminate gracefully when a SIGINT, SIGTERM signals are raised.

**Comment by jr0me** [comment]
### Update

Found that Vcpkg will include the include paths for all dependencies automatically to all projects and subprojects. This means that child components don't need to call `target_include_directories` and can include headers from dependencies specified from other sibling or parent projects. See: https://github.com/microsoft/vcpkg/discussions/40307

This is not a problem by itself, however it makes it easier to break encapsulation of dependencies and to forget to correctly include directories and link libraries where I needs to happen.

**Comment by jr0me** [comment]
### Update

Completed refactor of http request code from `Communicator` and `Register` to `http_client` namespace. Continuing with UTs.

**Comment by jr0me** [comment]
### Update

Most items listed in the issue are now resolved. The creation of a Logger was initially attempted using `spdlog` but without further research and design, it will bring little improvement over standard `cerr` and `cout`. The library looks promising but requires its own story to integrate.
