### ISSUE TITLE
false positive for macOS "File Vault is Enabled" because of script definition

### ISSUE THREAD

**Issue by l-with** [wazuh/wazuh-agent#73]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| v4.8.1 | agent | Agent | Packages | macOS Sonoma 14.6.1 |

`/Library/Ossec/bin/wazuh-control info`

```
WAZUH_VERSION="v4.8.1"
WAZUH_REVISION="40817"
WAZUH_TYPE="agent"
```

The rule definition in id 45025 for macOS 14 contains 
```yaml
    rules:
      - "c:fdesetup status -> r:^FileVault is On"
      - 'c:osascript -l JavaScript -e "osascript -l JavaScript -e "$.NSUserDefaults.alloc.initWithSuiteName(''com.apple.MCX'').objectForKey(''dontAllowFDEDisable'')" -> r:^0$'
```
The osacript fails because it is not correct and produces a false positiv. (I tried this out.)

Same certainly will happen on macOS 13 because of the rule definition in id 31025 
```yaml
    rules:
      - "c:fdesetup status -> r:^FileVault is On"
      - 'c:osascript -l JavaScript -e "osascript -l JavaScript -e "$.NSUserDefaults.alloc.initWithSuiteName(''com.apple.MCX'').objectForKey(''dontAllowFDEDisable'')" -> r:^0$'
```

**Comment by TomasTurina** [comment]
Fixed: https://github.com/wazuh/wazuh-agent/pull/74
