### ISSUE TITLE
Develop the Agent Command Handler

### ISSUE THREAD

**Issue by lchico** [wazuh/wazuh-agent#83]
**Parent issue:**
- https://github.com/wazuh/wazuh/issues/22887

## Description
Based on issue #4, we need to implement a command manager that executes the commands placed in the queue and provides feedback.

The following diagram is taken from [#4](https://github.com/wazuh/wazuh-agent/issues/4#issuecomment-2180316838)

```mermaid
sequenceDiagram
    participant Server
    participant AgentCommsAPIClient
    participant CommandManager
    participant CommandStore
    participant Executor
    participant Feedback

    AgentCommsAPIClient->>Server: getConnection()
    AgentCommsAPIClient->>Server: pollCommands()
    Server->>AgentCommsAPIClient: sendCommand()
    AgentCommsAPIClient->>CommandManager: addCommands()
    CommandManager->>CommandStore: storeCommand()
    CommandManager->>Executor: executeCommand()
    Executor->>CommandStore: getNextCommand()
    Executor->>Executor: execute()
    Executor->>Feedback: generateFeedback()
    Executor->>CommandManager: reportFeedback()
    CommandManager->>CommandStore: markCompleted()
    CommandStore->>CommandStore: deleteCompletedCommands()
    CommandManager->>AgentCommsAPIClient: reportFeedback()
    AgentCommsAPIClient->>Server: reportFeedback()
```

## Functional requirements
1. Commands persist on the agent: upon execution, they are marked as completed and reported to the manager.
2. Each command generates a result indicating completion status and outcome (success or error) with enough clarity for the user to take appropriate action.
3. Completed commands are deleted from the agent once the manager confirms receipt of the result.
4. All commands must be executed in the order of creation.

## Implementation restrictions

1. **Language:**
    We want to use C++ to leverage its performance and system-level capabilities.
2. **Modular integration:**
    This module should be implemented as a library to ensure modularity and reusability, allowing it to be integrated seamlessly with other modules.
3. **Process tied:**
    This module will be tied to the main process of the agent, ensuring it operates as a core component of the agent's functionality.

**Comment by aritosteles** [comment]
# Update
- **(2024/08/14)**: Understanding issue requirements and getting acquainted with status of related issues.
- - Created work branch and added basic module structure.
- - Added placeholder coroutine to get commands from queue.
- - At the moment @LucioDonda is working on the Queue module and @jr0me is working on the integration with the existing modules.

**Comment by LucioDonda** [comment]
Hi @aritosteles, sorry for the late response, the first iteration of the queue is already merged:
[Issue](https://github.com/wazuh/wazuh-agent/issues/16) [PR](https://github.com/wazuh/wazuh-agent/pull/28)

**Comment by lchico** [comment]
# Update
- Review the existing code to understand how to implement the command manager.
- Consider how to implement a dummy module for testing purposes.
- Synchronize with the team to collect additional information.

**Comment by TomasTurina** [comment]
## Command Store

As part of the development of the _Command Manager_, a _Command Store_ is needed to persist the commands that are being executed. To do this, we will take advantage of the SQLite wrapper class developed as part of the _Queue_ component, but which requires the following changes:

- The functions that execute queries must be generic.
- All queries must be located in a single file.
- A new class needs to be created for the _Command Store_, similar to `MultiTypeQueue`.

cc @aritosteles @jr0me @cborla

**Comment by cborla** [comment]
Based on what we discussed at the meeting where the command store was evaluated, the sequence diagram would be as follows.

``` mermaid
sequenceDiagram
    participant Manager
    participant Communicator
    participant Queue
    participant CommandManager
    participant CommandStore
    participant Module

    Manager->>Communicator: Sends poll of commands
    Communicator->>Queue: Store for commands
    CommandManager ->> Queue: Get command (retrive)
    Queue -->> CommandManager: 
    CommandManager->>CommandStore: Stores commands 
    CommandManager->>Queue: Deletes commands (pop)
    CommandManager->>CommandManager: Analyzes corresponding module
    CommandManager->>Module: Starts coroutine with command and callback + transaction event
    Module->>CommandStore: Callback - Updates status and result
    CommandStore->>CommandManager: Notification of update
    CommandManager->>Queue: Sotore stateful message with result
    CommandManager->>CommandStore: Deletes command (pop)
    Communicator->>Queue: Polls for stateful events (retrive)
    Queue->>Communicator: Delivers stateful event
    Communicator->>Manager: Sends stateful event
    Manager->>Communicator: Acknowledges receipt
    Communicator->>Queue: Deletes stateful event (pop)

```
Please @aritosteles @jr0me @TomasTurina check to ensure that any modifications are adjusted accordingly.

**Comment by vikman90** [comment]
@TomasTurina @cborla thank you for the detailed explanation regarding the `CommandStore` and the use of SQLite. I agree that SQLite is a good choice, but I believe we should aim for a higher level of abstraction. While `CommandStore` will use a database wrapper, it should be agnostic of whether the underlying database is SQLite, MariaDB, or any other.

I’m unclear on the second point mentioned:
> All queries must be located in a single file.

Could you please elaborate on this?

Regarding the sequence diagram, one point that stands out to me is the direct callback from the `Module` to the `CommandStore`. Given that the `CommandManager` is orchestrating the process and also initiating the command to the Module, it would be cleaner for the `CommandStore` to remain a private member of the `CommandManager`. It might be better if the `Module` calls the `CommandManager`, and the `CommandManager` then registers the necessary information in the `CommandStore`.

Aside from these points, everything else makes sense, and I’m aligned with the overall approach.

**Comment by aritosteles** [comment]
# Updated sequence diagram:
``` mermaid
sequenceDiagram
    participant Manager
    participant Communicator
    participant Queue
    participant CommandManager
    participant CommandStore
    participant Module

    Manager->>Communicator: Sends poll of commands
    Communicator->>Queue: Store for commands
    CommandManager ->> Queue: Get command (retrive)
    Queue -->> CommandManager: 
    CommandManager->>CommandStore: Stores commands 
    CommandManager->>Queue: Deletes commands (pop)
    CommandManager->>CommandManager: Analyzes corresponding module
    CommandManager->>Module: Starts coroutine with command and callback + transaction event
    Module->>CommandManager: Callback - Updates status and result
    CommandManager->>CommandStore: Deletes command (pop)   
    CommandManager->>Queue: Store stateful message with result
    Communicator->>Queue: Polls for stateful events (retrive)
    Queue->>Communicator: Delivers stateful event
    Communicator->>Manager: Sends stateful event
    Manager->>Communicator: Acknowledges receipt
    Communicator->>Queue: Deletes stateful event (pop)

```

**Comment by Nicogp** [comment]
## Update

(2024/08/28):

- Review of the CommandManager development so far
- I have started the creation of the CommandStore class structure.
