### ISSUE TITLE
Increase the testing coverage of the new agent

### ISSUE THREAD

**Issue by TomasTurina** [wazuh/wazuh-agent#93]
## Description

In order to begin completing the development of the new agent, making it more robust, it is necessary to increase the test coverage of the new features and functionalities.

The following components must be tested and/or have their test coverage increased:
- [x] Communicator.
  - [x] Communicator.
  - [x] HTTP Client.
- [x] Register.
- [x] Task Manager.

Additionally, the tests must be compiled and run on GHA (without errors) on the following OS:
- [x] Linux.
- [x] Windows.
- [x] macOS.

**Comment by jr0me** [comment]
### Update

PR is in draft mode for the first steps, which are enabling macOS and Windows builds on the build and test pipelines. Some modifications were needed to fix compilation on Windows.

**Comment by jr0me** [comment]
### Update

MacOS and Windows builds are now enabled on Github Actions.

Looking into adding gcov to analyze testing coverage.

**Comment by jr0me** [comment]
### Update

Added a coverage check and report (downloadable as an artifact) github action. From this check future PRs will be able to verify that they are not decreasing coverage. Using this as starting point I'm making some changes to make some of our components more testable where we have the least test coverage.

**Comment by jr0me** [comment]
### Update

Increased coverage of `Register` functions and `SignalHandler` and `Agent` classes.

Working on doing the same for `Communicator` and `HttpClient`.

**Comment by jr0me** [comment]
### Update

Separated `HttpClient` socket and resolver parts into distinct class to be able to mock them. Wrote tests for `PerformHttpRequest`. Refactoring of the `HttpClient` class even further to make it "messages" agnostic.

**Comment by jr0me** [comment]
### Update

Working on testing `Co_PerformHttpRequest`.

**Comment by jr0me** [comment]
### Update

Coverage has been increased to 89%. Looking at the lines without coverage, further efforts won't bring enough gains (ie: missing coverage on catch blocks, which would require to mock some calls by introducing further interfaces, "glue code" from `http_socket` and `http_resolver`). Moving to fix compiler warnings and clang tidy checks.

**Comment by jr0me** [comment]
### Update

Fixed compiler warnings and clang tidy warnings. Added new clang format checks. Modified Github workflows to also run clang-tidy. PR is open for review.
